const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const data=await fetch('./data/trip.json').then(r=>r.json());
const tz=data.trip.timezone||'Europe/Rome',timeFmt=new Intl.DateTimeFormat('fr-FR',{timeZone:tz,hour:'2-digit',minute:'2-digit'}),dateFmt=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'});
const placeById=Object.fromEntries(data.places.map(p=>[p.id,p])),typeIcon={transfert:'🚢',balade:'🥾',repas:'🍝',marche:'🚶',bus:'🚌',plage:'🏖️',pause:'☕'};
const originalSchedule=structuredClone(data.days),SCHEDULE_KEY='st-schedule-v3';
let selectedDay=data.days.some(d=>d.date===dateFmt.format(new Date()))?dateFmt.format(new Date()):data.days[0].date,map,routeLayer,userMarker,accuracyLayer,trailLayer,watchId=null,userPosition=null,gpsTrail=[],editingDay=null,editingIndex=-1,deferredPrompt,toastTimer;
function eventDate(d,t){return new Date(`${d}T${t}:00+02:00`)}
function mins(t){const[h,m]=t.split(':').map(Number);return h*60+m}function fromM(v){v=((v%1440)+1440)%1440;return`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`}
function showToast(t){const e=$('#toast');e.textContent=t;e.classList.add('is-visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('is-visible'),2600)}
function saveSchedule(){const s={};data.days.forEach(d=>s[d.date]=d.events.map(e=>({time:e.time,end:e.end})));localStorage.setItem(SCHEDULE_KEY,JSON.stringify(s))}
function loadSchedule(){try{const s=JSON.parse(localStorage.getItem(SCHEDULE_KEY)||'{}');data.days.forEach(d=>(s[d.date]||[]).forEach((x,i)=>{if(d.events[i]&&x?.time&&x?.end){d.events[i].time=x.time;d.events[i].end=x.end}}))}catch{}}
loadSchedule();
function currentOrNext(now=new Date()){const all=data.days.flatMap(d=>d.events.map(e=>({...e,day:d,start:eventDate(d.date,e.time),finish:eventDate(d.date,e.end)})));return all.find(x=>now>=x.start&&now<x.finish)||all.find(x=>x.start>now)||all.at(-1)}
function hav(a,b){const R=6371,r=x=>x*Math.PI/180,d1=r(b.lat-a.lat),d2=r(b.lng-a.lng),x=Math.sin(d1/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function dist(k){return k<1?`${Math.round(k*1000)} m`:`${k.toFixed(1)} km`}
function bearing(a,b){const r=x=>x*Math.PI/180,d=x=>x*180/Math.PI,p1=r(a.lat),p2=r(b.lat),dl=r(b.lng-a.lng),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(d(Math.atan2(y,x))+360)%360}
function compass(v){return['nord','nord-est','est','sud-est','sud','sud-ouest','ouest','nord-ouest'][Math.round(v/45)%8]}
function distanceTo(p){return userPosition?hav(userPosition,p):null}
function eventLinks(e){const p=placeById[e.placeId];return`<div class="timeline-actions">${e.calendarUrl?`<a class="mini-action" href="${e.calendarUrl}" target="_blank" rel="noreferrer">📅</a>`:''}${p?`<a class="mini-action" href="${p.waze}" target="_blank" rel="noreferrer">W</a>`:''}</div>`}
function renderDaySwitch(){$('#daySwitch').innerHTML=data.days.map((d,i)=>`<button class="${d.date===selectedDay?'is-active':''}" data-day="${d.date}">Jour ${i+1} · ${d.label.replace(/^[^ ]+ /,'')}</button>`).join('');$$('[data-day]').forEach(b=>b.onclick=()=>{selectedDay=b.dataset.day;renderDaySwitch();renderLive();drawRoute()})}
function renderLive(){const d=data.days.find(x=>x.date===selectedDay),now=new Date();$('#todayTimeline').innerHTML=d.events.map(e=>{const s=eventDate(d.date,e.time),f=eventDate(d.date,e.end),p=placeById[e.placeId],dd=p?distanceTo(p):null;return`<article class="timeline-item ${now>=s&&now<f?'is-current':''}"><div class="timeline-time">${e.time}</div><div><div class="timeline-title">${typeIcon[e.type]||'•'} ${e.title}</div><div class="timeline-place">${e.place} · jusqu’à ${e.end}${dd!==null?` · ${dist(dd)}`:''}</div></div>${eventLinks(e)}</article>`}).join('');renderNext()}
function renderNext(){const n=currentOrNext(),p=placeById[n.placeId],dd=p?distanceTo(p):null,now=new Date(),badge=now>=n.start&&now<n.finish?'Maintenant':(dateFmt.format(now)===n.day.date?'Prochaine étape':'Étape à venir');$('#nextCard').innerHTML=`<div class="next-card__visual" style="background-image:linear-gradient(180deg,rgba(10,32,38,.05),rgba(10,32,38,.65)),url('${p?.heroImage||''}')"></div><div class="next-card__content"><div class="next-card__badge">${badge}</div><h3>${typeIcon[n.type]||'•'} ${n.time} — ${n.title}</h3><p>${n.place} · jusqu’à ${n.end}${dd!==null?` · ${dist(dd)} de vous`:''}</p>${p?`<div class="visual-hint"><strong>Repère visuel :</strong> ${p.repere}</div><div class="history-box"><strong>Repère historique :</strong> ${p.historyShort||''}</div>`:''}<div class="next-actions">${n.calendarUrl?`<a href="${n.calendarUrl}" target="_blank" rel="noreferrer">📅 Agenda</a>`:''}${p?`<a href="${p.waze}" target="_blank" rel="noreferrer">Waze</a><button class="ghost-action" data-open="${p.id}">Voir la fiche</button>`:''}</div></div>`;$('[data-open]')?.addEventListener('click',e=>openPlace(e.currentTarget.dataset.open))}
function renderProgram(){$('#programDays').innerHTML=data.days.map((d,i)=>`<article class="day-card"><div class="day-card-head"><div><p class="kicker">Jour ${i+1}</p><h3>${d.label}</h3></div><button class="reset-mini" data-reset="${d.date}">Réinitialiser</button></div><p class="timeline-place">${d.subtitle}</p>${d.events.map((e,j)=>{const p=placeById[e.placeId];return`<div class="timeline-item timeline-item--visual"><div class="timeline-thumb">${p?`<img src="${p.heroImage}" alt="">`:''}</div><div><div class="timeline-title">${e.time} · ${typeIcon[e.type]||'•'} ${e.title}</div><div class="timeline-place">${e.place} · ${e.time}–${e.end}</div></div><div class="timeline-actions"><button class="mini-action" data-edit="${d.date}:${j}">✎</button>${p?`<button class="mini-action" data-place="${p.id}">👁</button>`:''}</div></div>`}).join('')}</article>`).join('');$$('[data-edit]').forEach(b=>b.onclick=()=>{const[d,i]=b.dataset.edit.split(':');openEditor(d,+i)});$$('[data-reset]').forEach(b=>b.onclick=()=>resetDay(b.dataset.reset));$$('[data-place]').forEach(b=>b.onclick=()=>openPlace(b.dataset.place))}
function openEditor(d,i){const e=data.days.find(x=>x.date===d).events[i];editingDay=d;editingIndex=i;$('#scheduleTitle').textContent=e.title;$('#schedulePlace').textContent=e.place;$('#scheduleStart').value=e.time;$('#scheduleEnd').value=e.end;$('#shiftFollowing').checked=true;$('#scheduleDialog').showModal()}
function saveEdit(){const d=data.days.find(x=>x.date===editingDay),e=d.events[editingIndex],ns=$('#scheduleStart').value,ne=$('#scheduleEnd').value,delta=mins(ns)-mins(e.time);e.time=ns;e.end=ne;if($('#shiftFollowing').checked&&delta)d.events.slice(editingIndex+1).forEach(x=>{x.time=fromM(mins(x.time)+delta);x.end=fromM(mins(x.end)+delta)});saveSchedule();$('#scheduleDialog').close();renderLive();renderProgram();showToast('Horaire mis à jour.')}
function resetDay(date){const a=originalSchedule.find(d=>d.date===date),b=data.days.find(d=>d.date===date);b.events.forEach((e,i)=>{e.time=a.events[i].time;e.end=a.events[i].end});saveSchedule();renderLive();renderProgram();showToast('Journée réinitialisée.')}
function renderPlaces(){$('#placesList').innerHTML=data.places.map(p=>`<article class="place place--visual"><div class="place-photo"><img src="${p.heroImage}" alt="${p.name}"></div><div class="place-content"><div class="place-icon">${p.icon}</div><h3>${p.name}</h3><p>${p.note}</p><div class="history-snippet">${p.historyShort||''}</div><div class="place-actions"><button class="link-btn" data-place="${p.id}">Fiche</button><a class="link-btn" href="${p.waze}" target="_blank" rel="noreferrer">Waze</a></div></div></article>`).join('');$$('[data-place]').forEach(b=>b.onclick=()=>openPlace(b.dataset.place))}
function renderDiscover(){$('#discoverCards').innerHTML=data.discover.map(x=>`<article class="discover-card discover-card--photo"><img class="discover-card__bg" src="${x.image}" alt="${x.title}"><div class="discover-card__overlay"></div><div class="discover-card__inner"><div class="icon">${x.icon}</div><h3>${x.title}</h3><p>${x.text}</p></div><button data-discover="${x.placeId}">Ouvrir</button></article>`).join('');$$('[data-discover]').forEach(b=>b.onclick=()=>openPlace(b.dataset.discover))}
function renderHistory(){const ids=['torre','faro','luna','brandali','rena','panorama'];$('#historyCards').innerHTML=data.places.filter(p=>ids.includes(p.id)).map(p=>`<article class="history-card"><img src="${p.heroImage}" alt="${p.name}"><div class="history-card__body"><h3>${p.icon} ${p.name}</h3><p class="history-card__short">${p.historyShort}</p><p>${p.historyLong}</p><button class="link-btn" data-history="${p.id}">Voir la fiche</button></div></article>`).join('');$$('[data-history]').forEach(b=>b.onclick=()=>openPlace(b.dataset.history))}
function openPlace(id){const p=placeById[id],dd=distanceTo(p);$('#dialogContent').innerHTML=`<div class="dialog-hero dialog-hero--photo"><img class="dialog-photo" src="${p.heroImage}" alt="${p.name}"><div class="dialog-hero__overlay"></div><div class="dialog-hero__content"><div class="dialog-icon">${p.icon}</div><h3>${p.name}</h3><p>${p.note}</p>${dd!==null?`<div class="dialog-distance">À ${dist(dd)} de votre position</div>`:''}</div></div><div class="dialog-body"><p>${p.description||p.detail}</p><div class="repere-box"><strong>Ce que vous voyez :</strong> ${p.arCue||p.repere}</div><div class="history-box"><strong>En bref :</strong> ${p.historyShort||''}</div><div class="history-box history-box--deep"><strong>Histoire :</strong> ${p.historyLong||p.detail}</div>${p.sourceUrl?`<p class="source-note">Source : <a href="${p.sourceUrl}" target="_blank" rel="noreferrer">${p.sourceLabel}</a></p>`:''}<div class="dialog-actions"><a href="${p.waze}" target="_blank" rel="noreferrer">Waze</a><a class="alt" href="https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}" target="_blank" rel="noreferrer">Maps</a></div></div>`;$('#placeDialog').showModal()}
function renderGuide(){if(!userPosition){$('#nearestPanel').hidden=true;$('#arGuidePanel').innerHTML='<div class="around-empty">Active le GPS : le commentaire du lieu le plus proche apparaîtra ici automatiquement.</div>';$('#aroundMePanel').innerHTML='<div class="around-empty">Active le suivi GPS pour classer les lieux par distance.</div>';return}const here=userPosition,list=data.places.map(p=>({...p,d:hav(here,p),dir:compass(bearing(here,p))})).sort((a,b)=>a.d-b.d),top=list.slice(0,4),c=top[0],n=currentOrNext(),ap=placeById[n.placeId];$('#nearestPanel').hidden=false;$('#nearestPanel').innerHTML=`<h3>Les plus proches</h3>${top.map(p=>`<div class="nearest-row"><span>${p.icon} ${p.name}</span><strong>${dist(p.d)} · ${p.dir}</strong></div>`).join('')}`;$('#arGuidePanel').innerHTML=`<article class="ar-guide-card"><div class="ar-guide-card__photo"><img src="${c.heroImage}" alt="${c.name}"></div><div class="ar-guide-card__body"><div class="around-card__top"><span class="around-rank">Guide augmenté</span><strong>${dist(c.d)} · ${c.dir}</strong></div><h3>${c.icon} ${c.name}</h3><p>${c.description||c.note}</p><div class="repere-box"><strong>Ce que vous regardez :</strong> ${c.arCue||c.repere}</div><div class="history-box"><strong>Repère historique :</strong> ${c.historyShort||''}</div><div class="history-box history-box--deep"><strong>Commentaire :</strong> ${c.historyLong||''}</div>${ap?`<div class="agenda-cue"><strong>Selon le programme :</strong> ${n.time} · ${n.title}${ap.id===c.id?' — vous êtes au bon endroit.':` — ${dist(hav(here,ap))} vers ${compass(bearing(here,ap))}`}<div class="place-actions"><a class="link-btn" href="${n.calendarUrl}" target="_blank" rel="noreferrer">📅 Agenda</a><a class="link-btn" href="${ap.waze}" target="_blank" rel="noreferrer">Waze</a></div></div>`:''}<button class="link-btn" data-ar="${c.id}">Fiche complète</button></div></article>`;$('[data-ar]').onclick=()=>openPlace(c.id);$('#aroundMePanel').innerHTML=top.map((p,i)=>`<article class="around-card"><div class="around-card__photo"><img src="${p.heroImage}" alt="${p.name}"></div><div class="around-card__body"><div class="around-card__top"><span class="around-rank">${i?'À proximité':'Le plus proche'}</span><strong>${dist(p.d)} · ${p.dir}</strong></div><h3>${p.icon} ${p.name}</h3><p>${p.historyShort||p.note}</p><button class="link-btn" data-around="${p.id}">Voir</button></div></article>`).join('');$$('[data-around]').forEach(b=>b.onclick=()=>openPlace(b.dataset.around))}
function initMap(){if(!window.L)return;map=L.map('map').setView([41.242,9.17],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);data.places.forEach(p=>L.marker([p.lat,p.lng]).addTo(map).bindPopup(`<b>${p.icon} ${p.name}</b><br>${p.note}<br><a href="${p.waze}" target="_blank">Waze</a>`));drawRoute()}
function drawRoute(){if(!map)return;if(routeLayer)map.removeLayer(routeLayer);const r=data.routes.find(x=>x.day===selectedDay),pts=r.points.map(id=>placeById[id]).filter(Boolean).map(p=>[p.lat,p.lng]);routeLayer=L.polyline(pts,{weight:4,opacity:.7,dashArray:'10,7'}).addTo(map);if(!userPosition)map.fitBounds(pts,{padding:[20,20]})}
function gpsPosition(pos){userPosition={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy};if(map){if(userMarker)map.removeLayer(userMarker);if(accuracyLayer)map.removeLayer(accuracyLayer);userMarker=L.circleMarker([userPosition.lat,userPosition.lng],{radius:9,weight:4,fillOpacity:1}).addTo(map);accuracyLayer=L.circle([userPosition.lat,userPosition.lng],{radius:userPosition.accuracy||20,weight:1,fillOpacity:.08}).addTo(map);gpsTrail.push([userPosition.lat,userPosition.lng]);if(gpsTrail.length>100)gpsTrail.shift();if(trailLayer)map.removeLayer(trailLayer);trailLayer=L.polyline(gpsTrail,{weight:3,opacity:.5}).addTo(map);map.setView([userPosition.lat,userPosition.lng],16)}$('#gpsStatus').hidden=false;$('#gpsStatusText').textContent='GPS actif · guide augmenté en direct';$('#gpsMeta').textContent=`Précision ±${Math.round(userPosition.accuracy||0)} m · ${timeFmt.format(new Date())}`;renderLive();renderProgram();renderGuide()}
function toggleGps(){if(watchId!==null){navigator.geolocation.clearWatch(watchId);watchId=null;$('#locateMe').textContent='◎ Démarrer le suivi GPS';$('#gpsStatusText').textContent='Suivi GPS arrêté';showToast('GPS arrêté.');return}if(!navigator.geolocation)return showToast('Géolocalisation indisponible.');$('#locateMe').textContent='GPS…';watchId=navigator.geolocation.watchPosition(gpsPosition,e=>{showToast('Autorisez la localisation précise.');watchId=null;$('#locateMe').textContent='◎ Démarrer le suivi GPS'},{enableHighAccuracy:true,maximumAge:1500,timeout:12000});$('#locateMe').textContent='■ Arrêter le suivi GPS'}
function renderPlaylist(){$('#playlist').innerHTML=data.playlist.map((t,i)=>`<div class="track"><span class="track-index">${String(i+1).padStart(2,'0')}</span><div><strong>${t.artist} — ${t.title}</strong><br><small>${t.moment}</small></div><a class="play-btn" target="_blank" rel="noreferrer" href="https://www.youtube.com/results?search_query=${encodeURIComponent(t.artist+' '+t.title)}">▶</a></div>`).join('')}
function renderChecklist(){const s=JSON.parse(localStorage.getItem('st-checklist')||'{}');$('#checklist').innerHTML=data.checklist.map((x,i)=>`<label class="check-row"><input type="checkbox" data-check="${i}" ${s[i]?'checked':''}><span>${x}</span></label>`).join('');$$('[data-check]').forEach(c=>c.onchange=()=>{const o={};$$('[data-check]').forEach(x=>o[x.dataset.check]=x.checked);localStorage.setItem('st-checklist',JSON.stringify(o))})}
function countdown(){const ms=eventDate(data.trip.start,'00:00')-new Date();$('#countdownValue').textContent=ms>0?`${Math.ceil(ms/86400000)} jours`:'En cours'}function network(){$('#networkBadge').textContent=navigator.onLine?'● En ligne':'● Hors ligne'}
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e});$('#installApp').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null}else showToast('Chrome → ⋮ → Ajouter à l’écran d’accueil.')};$('#shareTrip').onclick=async()=>navigator.share?navigator.share({title:data.trip.title,url:location.href}):navigator.clipboard?.writeText(location.href);$('#locateMe').onclick=toggleGps;$('#scheduleForm').onsubmit=e=>{e.preventDefault();saveEdit()};$('[data-close-dialog]').onclick=()=>$('#placeDialog').close();$('[data-close-schedule]').onclick=()=>$('#scheduleDialog').close();$('#resetDay').onclick=()=>{resetDay(editingDay);$('#scheduleDialog').close()};$$('[data-scroll]').forEach(b=>b.onclick=()=>$(b.dataset.scroll)?.scrollIntoView({behavior:'smooth'}));$$('.map-tab').forEach(b=>b.onclick=()=>{$$('.map-tab').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');const off=b.dataset.mapMode==='offline';$('#interactiveMapPanel').hidden=off;$('#offlineMapPanel').hidden=!off;if(!off&&map)setTimeout(()=>map.invalidateSize(),50)});window.addEventListener('online',network);window.addEventListener('offline',network);
renderDaySwitch();renderLive();renderProgram();renderPlaces();renderDiscover();renderHistory();renderPlaylist();renderChecklist();initMap();renderGuide();network();countdown();$('#localClock').textContent=timeFmt.format(new Date());setInterval(()=>{$('#localClock').textContent=timeFmt.format(new Date());renderNext()},30000);if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js');