import {loadPocketGuideRoute,packHandoffUrl} from './route-runtime.js';
import {haversineKm,bearingDeg,compassLabel,deltaHeading,normalizeHeading,projectPlaces,simulatedPositionForPlace} from './ar-core.js';
import {listSavedRoutes,saveRoutePack,loadSavedRoute,deleteSavedRoute} from './route-library.js';
import {validateRoutePack} from '../engine/routepack.js';

const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const qs=new URL(location.href).searchParams;
const config=await fetch('./data/v2-config.json',{cache:'no-store'}).then(r=>r.ok?r.json():({})).catch(()=>({}));
const runtime=await loadPocketGuideRoute({locationLike:window.location});
let pack=structuredClone(runtime.pack);
let placeById={};
const CONTEXT_HEADING_DELTA=15;
const CONTEXT_HEADING_MS=1200;
const CONTEXT_GPS_MS=5000;
const CONTEXT_GPS_MOVE_KM=.02;
const ORIENTATION_RENDER_MS=75;
const state={
  skipped:new Set(),currentPlaceId:null,position:null,heading:null,gpsWatch:null,map:null,userMarker:null,routeLayer:null,placeLayer:null,followMap:true,
  connected:false,connecting:false,listening:false,responding:false,pc:null,dc:null,micStream:null,lastAssistant:'',lastUser:'',processedCalls:new Set(),
  ar:false,arSimulation:false,cameraStream:null,orientationHandler:null,focusedPlaceId:null,demo:false,routeRevision:0,
  lastContextAt:0,lastContextHeading:null,lastContextPosition:null,lastOrientationRenderAt:0,proactiveEnabled:true
};

function rebuildPlaces(){placeById=Object.fromEntries((pack.places||[]).map(p=>[p.id,p]))}
rebuildPlaces();
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function kmText(km){if(!Number.isFinite(km))return'—';return km<1?`${Math.round(km*1000)} m`:`${km.toFixed(1)} km`}
function stateKey(){return`pg15-state-v2:${pack.id}`}
function eventIds(){return new Set((pack.days||[]).flatMap(d=>(d.events||[]).map(e=>e.id)))}
function persistState(){try{localStorage.setItem(stateKey(),JSON.stringify({skipped:[...state.skipped],currentPlaceId:state.currentPlaceId,focusedPlaceId:state.focusedPlaceId,routeRevision:state.routeRevision,followMap:state.followMap,proactiveEnabled:state.proactiveEnabled,updatedAt:new Date().toISOString()}))}catch{}}
function restoreState(){try{const saved=JSON.parse(localStorage.getItem(stateKey())||'null');if(!saved)return;const validEvents=eventIds();state.skipped=new Set((saved.skipped||[]).filter(id=>validEvents.has(id)));state.currentPlaceId=placeById[saved.currentPlaceId]?saved.currentPlaceId:null;state.focusedPlaceId=placeById[saved.focusedPlaceId]?saved.focusedPlaceId:null;state.routeRevision=Number(saved.routeRevision)||0;state.followMap=saved.followMap!==false;state.proactiveEnabled=saved.proactiveEnabled!==false}catch{}}
restoreState();

function allEvents(){return (pack.days||[]).flatMap(day=>(day.events||[]).map(event=>({day,event,place:placeById[event.placeId]}))).filter(x=>!state.skipped.has(x.event.id))}
function activeEvent(){const events=allEvents();if(state.currentPlaceId){const exact=events.find(x=>x.event.placeId===state.currentPlaceId);if(exact)return exact}const today=new Date().toLocaleDateString('en-CA',{timeZone:pack.timezone||'Europe/Paris'});const hm=new Date().toLocaleTimeString('fr-FR',{timeZone:pack.timezone||'Europe/Paris',hour:'2-digit',minute:'2-digit',hour12:false});const dayEvents=events.filter(x=>x.day.date===today);return dayEvents.find(x=>x.event.time<=hm&&hm<x.event.end)||dayEvents.find(x=>x.event.time>hm)||events[0]||null}
function nextEvent(){const events=allEvents(),cur=activeEvent();if(!cur)return events[0]||null;const i=events.findIndex(x=>x.event.id===cur.event.id);return events[i+1]||null}
function remainingEvents(){const events=allEvents(),cur=activeEvent();if(!cur)return events;const i=events.findIndex(x=>x.event.id===cur.event.id);return i<0?events:events.slice(i)}
function nearestPlaces(limit=5){if(!state.position)return[];return (pack.places||[]).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)).map(p=>({place:p,distanceKm:haversineKm(state.position,p),bearing:bearingDeg(state.position,p)})).sort((a,b)=>a.distanceKm-b.distanceKm).slice(0,limit)}
function nearestPlace(){return nearestPlaces(1)[0]||null}
function targetPlace(){return state.focusedPlaceId?placeById[state.focusedPlaceId]:(nearestPlace()?.place||activeEvent()?.place||pack.places?.[0]||null)}
function contextSnapshot(){const cur=activeEvent(),next=nextEvent(),near=nearestPlace(),target=targetPlace();return{app:'PocketGuide 1.5.1',route:{id:pack.id,title:pack.title,timezone:pack.timezone},now:new Date().toISOString(),position:state.position?{lat:+state.position.lat.toFixed(6),lng:+state.position.lng.toFixed(6),accuracy:Math.round(state.position.accuracy||0),simulated:Boolean(state.position.simulated)}:null,heading:Number.isFinite(state.heading)?Math.round(state.heading):null,nearest:near?{id:near.place.id,name:near.place.name,distanceMeters:Math.round(near.distanceKm*1000),bearing:Math.round(near.bearing)}:null,target:target?{id:target.id,name:target.name}:null,current:cur?{eventId:cur.event.id,title:cur.event.title,placeId:cur.event.placeId,place:cur.place?.name||cur.event.place,time:cur.event.time,end:cur.event.end}:null,next:next?{eventId:next.event.id,title:next.event.title,placeId:next.event.placeId,place:next.place?.name||next.event.place,time:next.event.time}:null,remaining:remainingEvents().length,skipped:[...state.skipped],arActive:state.ar,routeRevision:state.routeRevision}}

function guideInstructions(){return `Tu es PocketGuide 1.5, un excellent guide touristique vocal qui marche réellement avec le voyageur. Tu reçois son RoutePack, sa position GPS, son cap, sa cible Geo-AR et l'état du parcours. Priorité absolue : interaction naturelle, concise et utile sur le terrain. Parle en français, phrases courtes, chaleureuses, jamais comme une brochure. Quand l'utilisateur demande ce qu'il regarde, où il est, quoi faire ensuite, raccourcir ou modifier la balade, utilise les outils disponibles. Si une information n'est pas dans le RoutePack ou le contexte, dis-le simplement. Tu peux être interrompu. Pour un lieu, raconte en priorité ce qui est visible, puis une histoire ou un détail culturel mémorable. Ne surcharge pas le voyageur de dates. Si le GPS ou le cap manque, demande d'activer le contexte plutôt que d'inventer.`}
const tools=[
  {type:'function',name:'get_trip_state',description:'Lire la position, le cap, la cible AR, l’étape courante et la suite.',parameters:{type:'object',properties:{},additionalProperties:false}},
  {type:'function',name:'get_nearby_places',description:'Lister les lieux RoutePack les plus proches.',parameters:{type:'object',properties:{limit:{type:'integer',minimum:1,maximum:6}},additionalProperties:false}},
  {type:'function',name:'focus_place_in_ar',description:'Définir un lieu RoutePack comme cible AR.',parameters:{type:'object',properties:{placeId:{type:'string'}},required:['placeId'],additionalProperties:false}},
  {type:'function',name:'skip_next_stop',description:'Supprimer la prochaine étape du parcours.',parameters:{type:'object',properties:{reason:{type:'string'}},additionalProperties:false}},
  {type:'function',name:'go_to_place',description:'Choisir un lieu comme nouvelle étape courante.',parameters:{type:'object',properties:{placeId:{type:'string'}},required:['placeId'],additionalProperties:false}},
  {type:'function',name:'shorten_route',description:'Raccourcir le parcours en retirant les étapes futures les moins prioritaires sans supprimer les incontournables.',parameters:{type:'object',properties:{removeCount:{type:'integer',minimum:1,maximum:4}},additionalProperties:false}},
  {type:'function',name:'open_ar',description:'Activer la vue Geo-AR.',parameters:{type:'object',properties:{},additionalProperties:false}}
];
function priorityOf(x){const raw=x?.event?.priority??x?.place?.priority??50;if(typeof raw==='string'){const k=raw.toLowerCase();if(/must|incontourn|high|haute/.test(k))return 90;if(/low|basse|option/.test(k))return 20}const n=Number(raw);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):50}
function isMustSee(x){return Boolean(x?.event?.mustSee||x?.place?.mustSee||priorityOf(x)>=80)}
function toolCall(name,args={}){
  if(name==='get_trip_state')return contextSnapshot();
  if(name==='get_nearby_places'){if(!state.position)return{error:'GPS indisponible'};return nearestPlaces(Math.max(1,Math.min(6,args.limit||4))).map(x=>({id:x.place.id,name:x.place.name,distanceMeters:Math.round(x.distanceKm*1000),direction:compassLabel(x.bearing),description:x.place.historyShort||x.place.description||''}))}
  if(name==='focus_place_in_ar'){if(!placeById[args.placeId])return{error:'Lieu inconnu'};state.focusedPlaceId=args.placeId;persistState();renderAll();return{ok:true,target:placeById[args.placeId].name}}
  if(name==='skip_next_stop'){const n=nextEvent();if(!n)return{error:'Aucune étape suivante'};state.skipped.add(n.event.id);state.routeRevision++;persistState();renderAll();return{ok:true,skipped:n.event.title,next:nextEvent()?.event.title||null}}
  if(name==='go_to_place'){const p=placeById[args.placeId];if(!p)return{error:'Lieu inconnu'};state.currentPlaceId=p.id;state.focusedPlaceId=p.id;state.routeRevision++;persistState();renderAll();return{ok:true,current:p.name}}
  if(name==='shorten_route'){const count=Math.max(1,Math.min(4,args.removeCount||1));const candidates=remainingEvents().slice(1).filter(x=>!x.event.fixed&&!x.event.locked&&!['transfert','bus','train','ferry','flight','avion','navette'].includes(String(x.event.type||'').toLowerCase())&&!isMustSee(x)).sort((a,b)=>priorityOf(a)-priorityOf(b));const removed=[];for(const x of candidates){if(removed.length>=count)break;state.skipped.add(x.event.id);removed.push(x.event.title)}state.routeRevision++;persistState();renderAll();return{ok:true,removed,preservedMustSee:true,next:nextEvent()?.event.title||null}}
  if(name==='open_ar'){void toggleAR(true);return{ok:true}}
  return{error:`Outil inconnu: ${name}`}
}

function addTurn(role,text){if(!text)return;const el=document.createElement('div');el.className=`turn turn--${role}`;el.innerHTML=`${esc(text)}<small>${role==='user'?'Vous':'PocketGuide'} · ${new Date().toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})}</small>`;$('#conversationLog').append(el);$('#conversationLog').scrollTop=$('#conversationLog').scrollHeight;if(role==='assistant'){state.lastAssistant=text;$('#guideAnswer').textContent=text}else state.lastUser=text}
function setSession(text,live=false){$('#sessionState').textContent=text;$('#sessionState').classList.toggle('is-live',live);$('#voiceMain').classList.toggle('is-live',live);$('#voiceLabel').textContent=live?(state.listening?'Je vous écoute…':state.responding?'Le guide vous répond…':'Guide IA connecté'):'Parlez à votre guide'}
function sendEvent(payload){if(state.dc?.readyState!=='open')return false;state.dc.send(JSON.stringify(payload));return true}
function shouldSendContext(reason,force=false){if(force)return true;const now=Date.now();if(reason==='cap'){if(!Number.isFinite(state.heading))return false;if(now-state.lastContextAt<CONTEXT_HEADING_MS)return false;if(Number.isFinite(state.lastContextHeading)&&Math.abs(deltaHeading(state.heading,state.lastContextHeading))<CONTEXT_HEADING_DELTA)return false;return true}if(reason==='gps'){if(!state.position)return false;const moved=state.lastContextPosition?haversineKm(state.lastContextPosition,state.position):Infinity;return moved>=CONTEXT_GPS_MOVE_KM||now-state.lastContextAt>=CONTEXT_GPS_MS}return now-state.lastContextAt>=900}
function sendContext(reason='terrain',{force=false}={}){if(!state.connected||!shouldSendContext(reason,force))return false;state.lastContextAt=Date.now();state.lastContextHeading=state.heading;state.lastContextPosition=state.position?{lat:state.position.lat,lng:state.position.lng}:null;return sendEvent({type:'session.update',session:{type:'realtime',instructions:`${guideInstructions()}\nContexte terrain actuel (${reason}) : ${JSON.stringify(contextSnapshot())}`}})}
function askRealtime(text){addTurn('user',text);sendContext('question',{force:true});sendEvent({type:'conversation.item.create',item:{type:'message',role:'user',content:[{type:'input_text',text}]}});sendEvent({type:'response.create',response:{instructions:'Réponds comme le guide terrain PocketGuide, brièvement et utilement.'}})}
function extractResponseText(evt){const chunks=[];for(const item of evt?.response?.output||[]){for(const c of item?.content||[]){if(c?.text)chunks.push(c.text);if(c?.transcript)chunks.push(c.transcript)}}return chunks.join(' ').trim()}
async function executeTool(name,callId,argsText){if(callId&&state.processedCalls.has(callId))return;if(callId)state.processedCalls.add(callId);let args={};try{args=JSON.parse(argsText||'{}')}catch{}const result=toolCall(name,args);sendEvent({type:'conversation.item.create',item:{type:'function_call_output',call_id:callId,output:JSON.stringify(result)}});sendContext('outil',{force:true});sendEvent({type:'response.create'});return result}
async function handleRealtimeEvent(evt){
  if(evt.type==='response.created'){state.responding=true;setSession('Réponse',true);return}
  if(evt.type==='input_audio_buffer.speech_started'){state.listening=true;setSession('Écoute',true);return}
  if(evt.type==='input_audio_buffer.speech_stopped'){state.listening=false;setSession(state.responding?'Réponse':'IA',true);return}
  if(evt.type==='conversation.item.input_audio_transcription.completed'&&evt.transcript&&evt.transcript!==state.lastUser)addTurn('user',evt.transcript);
  if(evt.type==='response.output_audio_transcript.done'&&evt.transcript&&evt.transcript!==state.lastAssistant)addTurn('assistant',evt.transcript);
  if(evt.type==='response.output_text.done'&&evt.text&&evt.text!==state.lastAssistant)addTurn('assistant',evt.text);
  if(evt.type==='response.done'){state.responding=false;const text=extractResponseText(evt);if(text&&text!==state.lastAssistant)addTurn('assistant',text);setSession('IA',true)}
  if(evt.type==='response.function_call_arguments.done')return executeTool(evt.name,evt.call_id,evt.arguments);
  if(evt.type==='response.output_item.done'&&evt.item?.type==='function_call')return executeTool(evt.item.name,evt.item.call_id,evt.item.arguments);
  if(evt.type==='error'){state.responding=false;addTurn('assistant',`Erreur IA : ${evt.error?.message||'inconnue'}`);setSession('IA erreur')}
}
async function connectRealtime(){if(state.connected||state.connecting)return;if(!config.apiBase){addTurn('assistant','Le pont IA n’est pas configuré.');return}state.connecting=true;try{setSession('Connexion…');const pc=new RTCPeerConnection();state.pc=pc;pc.ontrack=e=>{const audio=$('#remoteAudio');audio.srcObject=e.streams[0];audio.play().catch(()=>{})};pc.onconnectionstatechange=()=>{if(['failed','closed'].includes(pc.connectionState)){state.connected=false;state.responding=false;setSession('IA')}};const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true}});state.micStream=stream;stream.getTracks().forEach(t=>pc.addTrack(t,stream));const dc=pc.createDataChannel('oai-events');state.dc=dc;dc.onmessage=e=>{try{void handleRealtimeEvent(JSON.parse(e.data))}catch{}};dc.onclose=()=>{state.connected=false;state.responding=false;setSession('IA')};dc.onopen=()=>{state.connected=true;state.connecting=false;sendEvent({type:'session.update',session:{type:'realtime',instructions:`${guideInstructions()}\nContexte initial : ${JSON.stringify(contextSnapshot())}`,tools,tool_choice:'auto',audio:{input:{noise_reduction:{type:'near_field'},transcription:{model:'gpt-4o-mini-transcribe',language:'fr'},turn_detection:{type:'semantic_vad',create_response:true,interrupt_response:true}},output:{voice:config.voice||'marin'}}}});state.lastContextAt=Date.now();state.lastContextHeading=state.heading;state.lastContextPosition=state.position?{lat:state.position.lat,lng:state.position.lng}:null;sendEvent({type:'response.create',response:{instructions:'Salue le voyageur en une phrase et indique que tu es prêt à le guider.'}});setSession('IA',true)};const offer=await pc.createOffer();await pc.setLocalDescription(offer);const endpoint=`${String(config.apiBase).replace(/\/$/,'')}/v2/realtime/call?model=${encodeURIComponent(config.realtimeModel||'gpt-realtime-2.1')}&voice=${encodeURIComponent(config.voice||'marin')}`;const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/sdp'},body:offer.sdp});if(!r.ok)throw new Error((await r.text())||`HTTP ${r.status}`);await pc.setRemoteDescription({type:'answer',sdp:await r.text()});$('#remoteAudio').play().catch(()=>{})}catch(error){state.connecting=false;disconnectRealtime();addTurn('assistant',`Connexion vocale indisponible : ${error.message||error}`)}}
function disconnectRealtime(){try{state.dc?.close()}catch{}try{state.pc?.close()}catch{}state.micStream?.getTracks?.().forEach(t=>t.stop());state.dc=null;state.pc=null;state.micStream=null;state.connected=false;state.connecting=false;state.listening=false;state.responding=false;state.processedCalls.clear();setSession('IA')}
function interrupt(){if(state.connected&&state.responding)sendEvent({type:'response.cancel'});state.responding=false;state.listening=false;setSession('IA',state.connected)}

function renderTerrain(){const cur=activeEvent(),target=targetPlace();$('#routeTitle').textContent=pack.title;$('#focusTitle').textContent=target?.name||cur?.event.title||pack.title;$('#focusEyebrow').textContent=state.ar?'Vision augmentée':'Maintenant';const description=target?.historyShort||target?.description||target?.note||cur?.event.note||'Parlez au guide pour découvrir ce lieu.';if(!state.lastAssistant||state.lastAssistant.startsWith('PocketGuide 1.5 chargé'))$('#guideAnswer').textContent=description;const hero=target?.heroImage;if(hero&&!state.ar){$('#terrainMedia').classList.add('has-photo');$('#terrainMedia').style.backgroundImage=`linear-gradient(180deg,rgba(3,14,17,.05),rgba(3,14,17,.8)),url("${hero}")`}else if(!state.ar){$('#terrainMedia').classList.remove('has-photo');$('#terrainMedia').style.backgroundImage=''}if(target&&state.position){const d=haversineKm(state.position,target),b=bearingDeg(state.position,target);$('#focusDistance').textContent=kmText(d);$('#focusDirection').textContent=compassLabel(b)}else{$('#focusDistance').textContent='—';$('#focusDirection').textContent='—'}$('#focusTime').textContent=cur?`${cur.event.time}–${cur.event.end}`:'—';$('#modeBadge').textContent=state.ar?(state.arSimulation?'AR DÉMO':Number.isFinite(state.heading)?'GEO-AR':'AR MANUEL'):'GUIDE'}
function renderNow(){const next=nextEvent(),near=nearestPlace(),rem=remainingEvents();$('#nowPlace').textContent=near?.place.name||activeEvent()?.place?.name||'Position inconnue';$('#nowDistance').textContent=near?`${kmText(near.distanceKm)} · ${compassLabel(near.bearing)}`:'Activez le GPS';$('#nextTitle').textContent=next?.event.title||'Fin du parcours';$('#nextMeta').textContent=next?`${next.event.time} · ${next.place?.name||next.event.place}`:'Profitez du lieu';$('#remainingTitle').textContent=`${rem.length} étape${rem.length>1?'s':''}`;$('#remainingMeta').textContent=rem.length?`${rem[0].event.time} → ${rem.at(-1).event.end}`:'Terminé'}
function renderTimeline(){const cur=activeEvent();$('#timeline').innerHTML=allEvents().map(x=>`<article class="timeline-item ${cur?.event.id===x.event.id?'is-current':''}" data-event="${esc(x.event.id)}"><div class="timeline-time">${esc(x.event.time)}</div><div><strong>${esc(x.event.title)}</strong><small>${esc(x.place?.name||x.event.place||'')}</small></div><button type="button" data-go="${esc(x.event.placeId||'')}">Voir</button></article>`).join('');$$('[data-go]').forEach(b=>b.onclick=()=>{if(b.dataset.go&&placeById[b.dataset.go]){state.currentPlaceId=b.dataset.go;state.focusedPlaceId=b.dataset.go;state.routeRevision++;persistState();renderAll();showPanel('guide',{terrain:true});sendContext('étape choisie',{force:true})}})}
function renderNearby(){const list=nearestPlaces(6);$('#nearbyList').innerHTML=list.length?list.map(x=>`<article class="nearby-item" role="button" tabindex="0" data-nearby="${esc(x.place.id)}"><strong>${esc(x.place.name)}</strong><small>${kmText(x.distanceKm)} · ${esc(compassLabel(x.bearing))}</small></article>`).join(''):'<p class="microcopy">Activez le GPS pour afficher les lieux proches.</p>';$$('[data-nearby]').forEach(el=>{const open=()=>{const p=placeById[el.dataset.nearby];if(!p)return;state.focusedPlaceId=p.id;persistState();renderAll();state.map?.setView([p.lat,p.lng],Math.max(state.map.getZoom(),16));sendContext('lieu proche',{force:true})};el.onclick=open;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}})}
function renderLibrary(){const items=listSavedRoutes();$('#libraryList').innerHTML=items.length?items.map(x=>`<div class="library-route" data-id="${esc(x.id)}"><div><strong>${esc(x.label||x.title)}</strong><small>${x.places||0} lieux</small></div><div><button class="ghost" data-open="${esc(x.id)}">Ouvrir</button><button class="ghost" data-delete="${esc(x.id)}">×</button></div></div>`).join(''):'<p class="microcopy">Aucun itinéraire sauvegardé.</p>';$$('[data-open]').forEach(b=>b.onclick=()=>openPack(loadSavedRoute(b.dataset.open)));$$('[data-delete]').forEach(b=>b.onclick=()=>{if(confirm('Supprimer cet itinéraire ?')){deleteSavedRoute(b.dataset.delete);renderLibrary()}})}
function renderAll(){renderTerrain();renderNow();renderTimeline();renderNearby();drawMapRoute();renderAR();refreshGpsButton()}

function initMap(){if(!window.L)return;state.map=L.map('map',{zoomControl:true});L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(state.map);state.map.on('dragstart zoomstart',()=>{if(state.gpsWatch!==null){state.followMap=false;persistState();refreshGpsButton()}});state.placeLayer=L.layerGroup().addTo(state.map);for(const p of pack.places||[]){if(!Number.isFinite(p.lat)||!Number.isFinite(p.lng))continue;const marker=L.circleMarker([p.lat,p.lng],{radius:7,weight:2,fillOpacity:.85}).addTo(state.placeLayer).bindPopup(`<strong>${esc(p.name)}</strong><br>${esc(p.historyShort||p.description||'')}`);marker.on('click',()=>{state.focusedPlaceId=p.id;persistState();renderAll();sendContext('marqueur carte',{force:true})})}const pts=(pack.places||[]).filter(p=>Number.isFinite(p.lat)&&Number.isFinite(p.lng)).map(p=>[p.lat,p.lng]);if(pts.length)state.map.fitBounds(pts,{padding:[20,20],maxZoom:15});drawMapRoute()}
function drawMapRoute(){if(!state.map)return;state.routeLayer?.remove();const pts=allEvents().map(x=>x.place).filter(p=>p&&Number.isFinite(p.lat)&&Number.isFinite(p.lng)).map(p=>[p.lat,p.lng]);if(pts.length>1)state.routeLayer=L.polyline(pts,{weight:4,opacity:.75,dashArray:'8,7'}).addTo(state.map)}
function updateMapPosition(){if(!state.map||!state.position)return;const ll=[state.position.lat,state.position.lng];if(!state.userMarker)state.userMarker=L.circleMarker(ll,{radius:9,weight:4,fillOpacity:1}).addTo(state.map).bindPopup('Vous êtes ici');else state.userMarker.setLatLng(ll);if(state.followMap)state.map.setView(ll,Math.max(16,state.map.getZoom()||16),{animate:true})}
function refreshGpsButton(){const b=$('#gpsBtn');if(!b)return;if(state.demo){b.textContent='◎ GPS démo';return}if(state.gpsWatch===null)b.textContent='◎ GPS';else if(!state.followMap)b.textContent='◎ Recentrer';else b.textContent='● GPS ON'}
function onPosition(pos){const previous=state.position;state.position={lat:pos.coords.latitude,lng:pos.coords.longitude,accuracy:pos.coords.accuracy||99};if(Number.isFinite(pos.coords.heading)&&Number(pos.coords.speed)>0.8&&!state.orientationHandler)state.heading=normalizeHeading(pos.coords.heading);const near=nearestPlace();if(near&&near.distanceKm<.14){const changed=state.currentPlaceId!==near.place.id;state.currentPlaceId=near.place.id;if(!state.focusedPlaceId)state.focusedPlaceId=near.place.id;if(changed)persistState()}$('#gpsState').textContent=`GPS ${Math.round(state.position.accuracy)}m`;$('#gpsState').classList.add('is-ok');updateMapPosition();renderAll();if(!previous||haversineKm(previous,state.position)>=.005)sendContext('gps')}
function startGps(){if(state.demo){updateMapPosition();return}if(state.gpsWatch!==null)return;if(!navigator.geolocation){addTurn('assistant','GPS indisponible sur ce navigateur.');return}state.followMap=true;state.gpsWatch=navigator.geolocation.watchPosition(onPosition,e=>{addTurn('assistant',`GPS : ${e.message||'indisponible'}`);$('#gpsState').classList.remove('is-ok')},{enableHighAccuracy:true,maximumAge:1500,timeout:15000});persistState();refreshGpsButton()}
function stopGps(){if(state.gpsWatch!==null){navigator.geolocation.clearWatch(state.gpsWatch);state.gpsWatch=null}$('#gpsState').textContent='GPS';$('#gpsState').classList.remove('is-ok');persistState();refreshGpsButton()}

function orientationAngle(){return Number(screen.orientation?.angle??window.orientation??0)||0}
function ensureManualARControls(show=false){let host=$('#arManualControls');if(!host){host=document.createElement('span');host.id='arManualControls';host.style.display='flex';host.style.gap='6px';for(const [label,delta] of [['↶ 15°',-15],['15° ↷',15]]){const b=document.createElement('button');b.type='button';b.className='glass-action';b.textContent=label;b.onclick=()=>{state.heading=normalizeHeading((state.heading??bearingDeg(state.position||targetPlace(),targetPlace()))+delta);renderAR();sendContext('cap manuel',{force:true})};host.append(b)}$('#terrain .terrain-topline')?.insertBefore(host,$('#arToggle'))}host.hidden=!show}
async function startOrientation(){if(state.orientationHandler)return Number.isFinite(state.heading);try{if(typeof DeviceOrientationEvent==='undefined')return false;if(typeof DeviceOrientationEvent.requestPermission==='function'){const p=await DeviceOrientationEvent.requestPermission();if(p!=='granted')return false}return await new Promise(resolve=>{let settled=false;const finish=v=>{if(settled)return;settled=true;resolve(v)};state.orientationHandler=e=>{let h=null;if(Number.isFinite(e.webkitCompassHeading))h=e.webkitCompassHeading;else if(Number.isFinite(e.alpha))h=normalizeHeading(360-e.alpha+orientationAngle());if(h===null)return;state.heading=normalizeHeading(h);const now=performance.now();if(now-state.lastOrientationRenderAt>=ORIENTATION_RENDER_MS){state.lastOrientationRenderAt=now;renderAR()}sendContext('cap');finish(true)};window.addEventListener('deviceorientationabsolute',state.orientationHandler,true);window.addEventListener('deviceorientation',state.orientationHandler,true);setTimeout(()=>finish(Number.isFinite(state.heading)),2500)})}catch{return false}}
function stopOrientation(){if(!state.orientationHandler)return;window.removeEventListener('deviceorientationabsolute',state.orientationHandler,true);window.removeEventListener('deviceorientation',state.orientationHandler,true);state.orientationHandler=null}
async function startCamera(){if(state.arSimulation)return true;if(state.cameraStream)return true;const stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:'environment'},width:{ideal:1920},height:{ideal:1080}},audio:false});state.cameraStream=stream;$('#arCamera').srcObject=stream;$('#arCamera').hidden=false;await $('#arCamera').play();return true}
function stopCamera(){state.cameraStream?.getTracks?.().forEach(t=>t.stop());state.cameraStream=null;$('#arCamera').pause?.();$('#arCamera').srcObject=null;$('#arCamera').hidden=true}
async function toggleAR(forceOn=false){if(state.ar&&!forceOn){state.ar=false;state.arSimulation=false;stopCamera();stopOrientation();ensureManualARControls(false);$('#arLabels').hidden=true;$('#arReticle').hidden=true;$('#arCompass').hidden=true;$('#arToggle').classList.remove('is-on');renderTerrain();sendContext('ar fermé',{force:true});return}state.ar=true;state.arSimulation=state.demo;$('#arToggle').classList.add('is-on');$('#arLabels').hidden=false;$('#arReticle').hidden=false;$('#arCompass').hidden=false;if(!state.position){const p=activeEvent()?.place||pack.places?.[0];if(state.demo&&p){state.position=simulatedPositionForPlace(p);state.heading=bearingDeg(state.position,p);updateMapPosition()}}if(!state.arSimulation){try{await startCamera();startGps();const orientationOk=await startOrientation();if(!orientationOk&&!Number.isFinite(state.heading)){const p=targetPlace();if(state.position&&p)state.heading=bearingDeg(state.position,p);ensureManualARControls(true);addTurn('assistant','Boussole indisponible : l’AR reste utilisable avec les réglages manuels ±15°.') }else ensureManualARControls(false)}catch(error){state.ar=false;stopCamera();stopOrientation();addTurn('assistant',`AR indisponible : ${error.message||error}`);$('#arToggle').classList.remove('is-on')}}renderAll();sendContext('ar',{force:true})}
function renderAR(){if(!state.ar||!state.position||!Number.isFinite(state.heading))return;const host=$('#arLabels');host.innerHTML='';const projected=projectPlaces({position:state.position,places:pack.places||[],heading:state.heading,fov:70,maxDistanceKm:25}).filter(x=>x.visible);$('#arCompass').textContent=`${Math.round(state.heading)}° · ${compassLabel(state.heading)}`;const width=host.clientWidth||innerWidth,height=host.clientHeight||innerHeight;projected.slice(0,8).forEach((item,i)=>{const el=document.createElement('button');el.className='ar-label';if(Math.abs(item.delta)<7)el.classList.add('is-focus');el.style.left=`${Math.max(.08,Math.min(.92,item.x))*width}px`;el.style.top=`${Math.max(82,Math.min(height*.62,height*(.25+(i%3)*.13)))}px`;el.innerHTML=`<strong>${esc(item.place.name)}</strong><small>${kmText(item.distanceKm)}</small>`;el.onclick=()=>{state.focusedPlaceId=item.place.id;persistState();renderAll();sendContext('cible ar',{force:true})};host.append(el)});const central=projected.slice().sort((a,b)=>Math.abs(a.delta)-Math.abs(b.delta))[0];if(central&&Math.abs(central.delta)<10&&state.focusedPlaceId!==central.place.id){state.focusedPlaceId=central.place.id;persistState()}}

function showPanel(name,{terrain=false}={}){const panel=$(`[data-panel="${name}"]`);$$('[data-panel]').forEach(p=>p.classList.toggle('is-active',p.dataset.panel===name));$$('[data-tab]').forEach(b=>b.classList.toggle('is-active',b.dataset.tab===name));if(name==='map')setTimeout(()=>state.map?.invalidateSize(),100);requestAnimationFrame(()=>{const target=terrain?$('#terrain'):panel;if(target){const top=target.getBoundingClientRect().top+scrollY-66;scrollTo({top:Math.max(0,top),behavior:'smooth'})}})}
function localReply(text){const v=String(text||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');const cur=targetPlace(),near=nearestPlace(),next=nextEvent();if(/raccour|moins de temps|fatigue/.test(v)){const r=toolCall('shorten_route',{removeCount:1});return r.removed?.length?`J’ai retiré ${r.removed.join(', ')} et conservé les étapes prioritaires.`:'Je n’ai trouvé aucune étape secondaire à retirer sans toucher aux incontournables.'}if(/saute|sauter|skip/.test(v)){const r=toolCall('skip_next_stop',{});return r.error?r.error:`Étape sautée : ${r.skipped}. La suite est ${r.next||'la fin du parcours'}.`}if(/ensuite|prochaine|continuer/.test(v))return next?`Ensuite : ${next.event.title}, à ${next.event.time}, vers ${next.place?.name||next.event.place||'le prochain repère'}.`:'Le parcours prévu est terminé.';if(/reste|resume|parcours|combien/.test(v)){const rem=remainingEvents();return rem.length?`Il reste ${rem.length} étape${rem.length>1?'s':''}, de ${rem[0].event.time} à ${rem.at(-1).event.end}.`:'Le parcours est terminé.'}if(/ou sommes|ou suis|ici|position/.test(v))return near?`Vous êtes à environ ${kmText(near.distanceKm)} de ${near.place.name}, direction ${compassLabel(near.bearing)}.`:(cur?`L’étape courante est ${cur.name}. Activez le GPS pour une position précise.`:'Activez le GPS pour vous situer.');if(/regarde|raconte|explique|lieu/.test(v))return cur?`${cur.name}. ${cur.historyShort||cur.description||cur.note||'Je n’ai pas encore de commentaire détaillé pour ce lieu.'}`:'Aucun lieu n’est ciblé.';if(/\bar\b|realite augmentee/.test(v)){void toggleAR(true);return'J’ouvre la réalité augmentée.'}return cur?`${cur.name}. ${cur.historyShort||cur.description||cur.note||'Activez le guide vocal pour une explication interactive.'}`:'Activez le GPS ou choisissez une étape pour commencer.'}
function submitCommand(text){const value=String(text||'').trim();if(!value)return;if(state.connected)askRealtime(value);else{addTurn('user',value);addTurn('assistant',localReply(value))}}
function openPack(newPack){if(!newPack)return;const report=validateRoutePack(newPack);if(!report.valid){alert(`RoutePack invalide : ${report.errors.map(x=>x.code).join(', ')}`);return}saveRoutePack(newPack,{source:'pocketguide-1.5'});const url=new URL(packHandoffUrl(newPack,location,sessionStorage));url.pathname=url.pathname.replace(/[^/]*$/,'pocketguide-15.html');location.href=url.toString()}
async function createPlan(){const prompt=$('#planPrompt').value.trim(),destination=$('#planDestination').value.trim();if(prompt.length<8){$('#planStatus').textContent='Décrivez un peu plus votre balade.';return}const base=String(config.apiBase||'').replace(/\/$/,'');if(!base){$('#planStatus').textContent='Worker AI non configuré.';return}$('#planBtn').disabled=true;$('#planStatus').textContent='AI Planner vérifie les lieux et prépare le RoutePack…';try{const r=await fetch(`${base}/v1/plan`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,destination,maxPlaces:Number($('#planPlaces').value)||5,timezone:pack.timezone||'Europe/Paris'})});const out=await r.json().catch(()=>({}));if(!r.ok)throw new Error(out.error||`HTTP ${r.status}`);if(!out.pack)throw new Error('RoutePack absent');const report=validateRoutePack(out.pack);if(!report.valid)throw new Error(`RoutePack invalide : ${report.errors.map(x=>x.code).join(', ')}`);saveRoutePack(out.pack,{source:'ai-planner-1.5.1'});$('#planStatus').textContent=`Parcours vérifié${out.verificationSources?.length?` · ${out.verificationSources.length} source(s)`:''}. Ouverture…`;openPack(out.pack)}catch(e){$('#planStatus').textContent=`Planner indisponible : ${e.message||e}`}finally{$('#planBtn').disabled=false}}
function requestProactiveGuide(place,distanceMeters){if(!place||!state.connected||state.listening||state.responding||state.dc?.readyState!=='open')return false;state.focusedPlaceId=place.id;persistState();renderAll();sendContext('arrivée monument',{force:true});state.responding=true;setSession('Réponse',true);return sendEvent({type:'response.create',response:{instructions:`Le voyageur vient d'arriver à environ ${Math.round(distanceMeters)} mètres de « ${place.name} ». Prends l'initiative comme un guide humain. Attire son attention sur ce qui est visible, utilise uniquement ces informations RoutePack : ${JSON.stringify({description:place.description||'',historyShort:place.historyShort||'',arCue:place.arCue||'',note:place.note||''})}. Parle moins de 20 secondes puis laisse-le poursuivre.`}})}

$('#voiceMain').onclick=async()=>{if(!state.connected)return connectRealtime();$('#remoteAudio').play().catch(()=>{});if(state.responding)return interrupt();setSession('IA',true)};
$('#interruptBtn').onclick=interrupt;
$('#arToggle').onclick=()=>toggleAR();
$('#gpsBtn').onclick=()=>{if(state.demo){state.followMap=true;updateMapPosition();return}if(state.gpsWatch===null)return startGps();if(!state.followMap){state.followMap=true;persistState();updateMapPosition();refreshGpsButton();return}stopGps()};
$('#clearLog').onclick=()=>$('#conversationLog').replaceChildren();
$('#routeReset').onclick=()=>{state.skipped.clear();state.currentPlaceId=null;state.focusedPlaceId=null;state.routeRevision++;persistState();renderAll();sendContext('parcours réinitialisé',{force:true})};
$('#textForm').onsubmit=e=>{e.preventDefault();submitCommand($('#textCommand').value);$('#textCommand').value=''};
$$('[data-command]').forEach(b=>b.onclick=()=>submitCommand(b.dataset.command));
$$('[data-ask]').forEach(b=>b.onclick=()=>{const map={where:'Où sommes-nous exactement et que faut-il observer ici ?',next:'Quelle est la prochaine étape et comment y aller intelligemment ?',remaining:'Résume-moi le reste du parcours et le temps restant.'};submitCommand(map[b.dataset.ask])});
$$('[data-tab]').forEach(b=>b.onclick=()=>showPanel(b.dataset.tab));
$('#planBtn').onclick=createPlan;
$('#importFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{openPack(JSON.parse(await f.text()))}catch(err){alert(`JSON invalide : ${err.message||err}`)}};
$('#startGuide').onclick=async()=>{$('#permissionSheet').hidden=true;startGps();await connectRealtime()};
$('#startDemo').onclick=()=>{state.demo=true;state.followMap=true;const p=activeEvent()?.place||pack.places?.[0];if(p){state.position=simulatedPositionForPlace(p);state.heading=bearingDeg(state.position,p);state.currentPlaceId=p.id;state.focusedPlaceId=p.id;$('#gpsState').textContent='GPS DÉMO';$('#gpsState').classList.add('is-ok');persistState();updateMapPosition()}$('#permissionSheet').hidden=true;renderAll();addTurn('assistant','Mode démo actif. Vous pouvez tester la voix, la carte et la réalité augmentée sans être sur place.')};
window.addEventListener('online',()=>{$('#networkState').textContent='● Réseau';$('#networkState').classList.add('is-ok')});
window.addEventListener('offline',()=>{$('#networkState').textContent='● Hors ligne';$('#networkState').classList.remove('is-ok')});
navigator.serviceWorker?.addEventListener?.('message',e=>{if(e.data?.type==='POCKETGUIDE_UPDATE_READY'){$('#networkState').textContent='● Mise à jour prête';$('#networkState').title='La mise à jour sera appliquée au prochain redémarrage de PocketGuide.'}});
window.addEventListener('beforeunload',()=>{persistState();disconnectRealtime();stopGps();stopCamera();stopOrientation()});

initMap();renderAll();renderLibrary();addTurn('assistant',`PocketGuide 1.5 chargé pour « ${pack.title} ». Je peux vous guider par la voix, le GPS et la réalité augmentée.`);if(qs.get('demo')==='1')$('#startDemo').click();else if(!sessionStorage.getItem('pg15-onboarded')){$('#permissionSheet').hidden=false;sessionStorage.setItem('pg15-onboarded','1')}
window.__POCKETGUIDE_15__={state,pack,contextSnapshot,toolCall,connectRealtime,toggleAR,openPack,sendContext,sendEvent,requestProactiveGuide,persistState,showPanel};