import {validateRoutePack} from '../engine/routepack.js';
import {packShareUrl,routeShareUrl} from './route-runtime.js';
const $=s=>document.querySelector(s);let current=null;
function slug(v){return String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,64)||'route'}
function parseSteps(text){return String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{const [time,end,title,lat,lng]=line.split('|').map(x=>x.trim());const id=`p${i+1}`;return {event:{id:`e${i+1}`,time,end,title:title||`Étape ${i+1}`,type:'balade',place:title||`Étape ${i+1}`,placeId:id},place:{id,name:title||`Étape ${i+1}`,lat:Number(lat),lng:Number(lng),icon:'📍',description:`Étape ${i+1} du parcours.`,note:title||`Étape ${i+1}`}}})}
function makePack(){const rows=parseSteps($('#steps').value),date=$('#date').value||new Date().toISOString().slice(0,10),id=slug($('#slug').value||$('#title').value);return {schemaVersion:'1.0',id,title:$('#title').value.trim()||'Mon parcours',timezone:$('#timezone').value.trim()||'Europe/Paris',travelers:Math.max(1,Number($('#travelers').value)||1),start:date,end:date,days:[{date,label:date,events:rows.map(r=>r.event)}],places:rows.map(r=>r.place),meta:{createdBy:'PocketGuide Studio V1.2',createdAt:new Date().toISOString()}}}
function show(pack){current=pack;const report=validateRoutePack(pack),lines=[`valid: ${report.valid}`,`${report.errors.length} erreur(s)`,`${report.warnings.length} avertissement(s)`];for(const e of report.errors)lines.push(`ERROR ${e.code} ${e.path}: ${e.message}`);for(const w of report.warnings)lines.push(`WARN ${w.code} ${w.path}: ${w.message}`);$('#status').innerHTML=report.valid?'<strong class="ok">✓ RoutePack valide</strong>':'<strong class="bad">✕ RoutePack invalide</strong>';$('#report').textContent=lines.join('\n');$('#preview').disabled=!report.valid;$('#share').disabled=!report.valid;$('#download').disabled=!report.valid;$('#shareUrl').value='';return report}
$('#build').onclick=()=>show(makePack());$('#title').addEventListener('input',()=>{$('#slug').value=slug($('#title').value)});
$('#importFile').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{show(JSON.parse(await f.text()))}catch(err){$('#status').innerHTML='<strong class="bad">JSON invalide</strong>';$('#report').textContent=String(err.message||err)}};
$('#preview').onclick=()=>{if(!current)return;location.href=packShareUrl(current,location)};
$('#share').onclick=async()=>{if(!current)return;try{const url=packShareUrl(current,location);if(url.length>12000)throw new Error('Le parcours est trop volumineux pour un lien autonome. Téléchargez le JSON et publiez-le dans le registre.');$('#shareUrl').value=url;await navigator.clipboard?.writeText(url)}catch(err){$('#shareUrl').value=String(err.message||err)}};
$('#download').onclick=()=>{if(!current)return;const blob=new Blob([JSON.stringify(current,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${current.id}.routepack.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};
(async()=>{try{const reg=await fetch('./data/routes.json',{cache:'no-store'}).then(r=>r.json());$('#routes').innerHTML=reg.routes.filter(r=>r.enabled!==false).map(r=>`<a href="${routeShareUrl(r.id,new URL('./engine.html',location.href))}">${r.title}</a>`).join('')}catch{$('#routes').textContent='Catalogue indisponible.'}})();
