import {validateRoutePack} from '../engine/routepack.js';
import {packHandoffUrl} from './route-runtime.js';
const $=s=>document.querySelector(s);let current=null,lastReport=null,apiBase='';const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function esc(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]))}
async function loadConfig(){try{const cfg=await fetch('./data/ai-config.json?v=1.4.7',{cache:'no-store'}).then(r=>r.ok?r.json():null);apiBase=String(cfg?.apiBase||'').replace(/\/$/,'')}catch{}const q=new URLSearchParams(location.search).get('api');if(q)apiBase=q.replace(/\/$/,'');$('#backend').textContent=apiBase?`Backend: ${apiBase}`:'Backend non configuré';}
function renderDraft(pack){if(!pack){$('#draft').textContent='Aucun brouillon.';return}$('#draft').innerHTML=`<h3>${esc(pack.title)}</h3><p>${esc(pack.start)} → ${esc(pack.end)} · ${(pack.places||[]).length} lieux</p>${(pack.days||[]).map(d=>`<div><strong>${esc(d.label||d.date)}</strong>${(d.events||[]).map(e=>`<p>${esc(e.time)}–${esc(e.end)} · ${esc(e.title)}</p>`).join('')}</div>`).join('')}`}
function setGate(valid,text){const g=$('#gate');g.className=`gate ${valid?'ready':'blocked'}`;g.innerHTML=valid?`<strong>✅ Validation déterministe réussie</strong><p>${esc(text||'RoutePack autorisé à entrer dans PocketGuide.')}</p>`:`<strong>🔒 PocketGuide verrouillé</strong><p>${esc(text||'Le RoutePack doit passer tous les contrôles bloquants.')}</p>`;$('#open').disabled=!valid}
function showPack(pack){current=pack;lastReport=null;const structural=validateRoutePack(pack);$('#validate').disabled=!structural.valid;$('#download').disabled=false;setGate(false,structural.valid?'Structure valide. Lancez maintenant le contrôle déterministe.':'La structure RoutePack est invalide.');$('#summary').textContent=[`Structure: ${structural.valid?'PASS':'FAIL'}`,`Erreurs: ${structural.errors.length}`,`Avertissements: ${structural.warnings.length}`,`Lieux: ${(pack.places||[]).length}`,...structural.errors.map(e=>`BLOCK ${e.code} ${e.path}: ${e.message}`)].join('\n');$('#sources').innerHTML='';renderDraft(pack)}
async function poll(taskId){const start=Date.now();while(Date.now()-start<240000){const r=await fetch(`${apiBase}/api/plan-status?id=${encodeURIComponent(taskId)}`,{cache:'no-store'});const p=await r.json().catch(()=>({}));if(r.status===202){$('#summary').textContent=`AI Planner en cours… ${Math.round((Date.now()-start)/1000)} s`;await sleep(2500);continue}if(!r.ok)throw new Error(p.error||`Erreur ${r.status}`);if(p.pack){showPack(p.pack);return}await sleep(2000)}throw new Error('Génération trop longue')}
async function generate(){const prompt=$('#prompt').value.trim();if(prompt.length<8)return alert('Décrivez un peu plus votre voyage.');if(!apiBase)return alert('Backend non configuré.');$('#generate').disabled=true;$('#summary').textContent='Démarrage AI Planner…';try{const r=await fetch(`${apiBase}/api/plan`,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({prompt,destination:$('#destination').value.trim(),timezone:'Europe/Paris',maxPlaces:Number($('#maxPlaces').value)||6})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`Erreur ${r.status}`);await poll(p.taskId)}catch(e){$('#summary').textContent=`AI ERROR: ${e.message||e}`}finally{$('#generate').disabled=false}}
async function validate(){if(!current||!apiBase)return;$('#validate').disabled=true;setGate(false,'Validation déterministe en cours…');$('#summary').textContent='Contrôle structure + dates + géographie + accessibilité des sources…';try{const r=await fetch(`${apiBase}/api/validate-routepack`,{method:'POST',headers:{'Content-Type':'text/plain;charset=UTF-8'},body:JSON.stringify({pack:current})});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||`Erreur ${r.status}`);lastReport=p;$('#summary').textContent=[`Validator: ${p.validatorVersion}`,`Déterministe: ${p.deterministic}`,`Résultat: ${p.valid?'PASS':'FAIL'}`,`Bloquants: ${p.summary?.blocking??0}`,`Avertissements: ${p.summary?.warnings??0}`,`Sources joignables: ${p.summary?.sourcesReachable??0}/${p.summary?.sources??0}`,...(p.blocking||[]).map(x=>`BLOCK ${x.code} ${x.path}: ${x.message}`),...(p.warnings||[]).map(x=>`WARN ${x.code} ${x.path}: ${x.message}`)].join('\n');$('#sources').innerHTML=(p.sources||[]).map(s=>`<div class="source"><strong>${s.reachable&&s.blocking.length===0?'✅':'❌'} ${esc(s.name||s.id)}</strong><small>${esc(s.sourceLabel)} · HTTP ${s.httpStatus??'—'}</small><br><small>${esc(s.sourceUrl)}</small>${s.warnings?.length?`<br><small>⚠ ${esc(s.warnings.join(', '))}</small>`:''}</div>`).join('');setGate(Boolean(p.valid),p.valid?'Toutes les conditions bloquantes sont satisfaites.':'Au moins un contrôle bloquant a échoué.');}catch(e){$('#summary').textContent=`VALIDATOR ERROR: ${e.message||e}`;setGate(false,'Validation impossible.')}finally{$('#validate').disabled=false}}
$('#generate').onclick=generate;$('#validate').onclick=validate;$('#open').onclick=()=>{if(!current||!lastReport?.valid)return;location.href=packHandoffUrl(current,location)};$('#download').onclick=()=>{if(!current)return;const blob=new Blob([JSON.stringify(current,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`${current.id}.routepack.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};await loadConfig();
