window.addEventListener('load',()=>{void initV5()},{once:true});

async function initV5(){
  const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
  const data=await fetch('./data/trip.json').then(r=>r.json());
  const tz=data.trip.timezone||'Europe/Rome';
  const timeFmt=new Intl.DateTimeFormat('fr-FR',{timeZone:tz,hour:'2-digit',minute:'2-digit'});
  const dateFmt=new Intl.DateTimeFormat('en-CA',{timeZone:tz,year:'numeric',month:'2-digit',day:'2-digit'});
  const dateTimeFmt=new Intl.DateTimeFormat('fr-FR',{timeZone:tz,dateStyle:'medium',timeStyle:'short'});
  const placeById=Object.fromEntries(data.places.map(p=>[p.id,p]));
  const KEYS={schedule:'st-schedule-v3',settings:'st-v5-settings',visits:'st-v5-visits',events:'st-v5-events',notes:'st-v5-notes',journey:'st-v5-journey'};
  let settings=read(KEYS.settings,{audioAuto:true}),visits=read(KEYS.visits,{}),events=read(KEYS.events,[]),notes=read(KEYS.notes,[]),journey=read(KEYS.journey,{distanceKm:0,startedAt:null,lastAt:null});
  let pos=null,lastTrack=null,v5Watch=null,lastAudioPlace=null,lastAudioId=null,lastAudioAt=0,proximity={},objectUrls=[];
  applySchedule();

  function read(k,f){try{return JSON.parse(localStorage.getItem(k)||'null')??f}catch{return f}}
  function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
  function toast(t){const e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('is-visible');setTimeout(()=>e.classList.remove('is-visible'),2800)}
  function eventDate(d,t){return new Date(`${d}T${t}:00+02:00`)}
  function mins(t){const[h,m]=t.split(':').map(Number);return h*60+m}
  function fromM(v){v=((v%1440)+1440)%1440;return`${String(Math.floor(v/60)).padStart(2,'0')}:${String(v%60).padStart(2,'0')}`}
  function isFixed(e){return e?.type==='bus'||/ferry|navette|bateau/i.test(e?.title||'')}
  function hav(a,b){const R=6371,r=x=>x*Math.PI/180,d1=r(b.lat-a.lat),d2=r(b.lng-a.lng),x=Math.sin(d1/2)**2+Math.cos(r(a.lat))*Math.cos(r(b.lat))*Math.sin(d2/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
  function dist(k){return k<1?`${Math.round(k*1000)} m`:`${k.toFixed(1)} km`}
  function bearing(a,b){const r=x=>x*Math.PI/180,d=x=>x*180/Math.PI,p1=r(a.lat),p2=r(b.lat),dl=r(b.lng-a.lng),y=Math.sin(dl)*Math.cos(p2),x=Math.cos(p1)*Math.sin(p2)-Math.sin(p1)*Math.cos(p2)*Math.cos(dl);return(d(Math.atan2(y,x))+360)%360}
  function compass(v){return['nord','nord-est','est','sud-est','sud','sud-ouest','ouest','nord-ouest'][Math.round(v/45)%8]}
  function applySchedule(){const s=read(KEYS.schedule,{});data.days.forEach(d=>(s[d.date]||[]).forEach((x,i)=>{if(d.events[i]&&x?.time&&x?.end){d.events[i].time=x.time;d.events[i].end=x.end}}))}
  function saveSchedule(){const s={};data.days.forEach(d=>s[d.date]=d.events.map(e=>({time:e.time,end:e.end})));write(KEYS.schedule,s)}
  function currentOrNext(now=new Date()){const all=data.days.flatMap(d=>d.events.map((e,index)=>({...e,index,day:d,start:eventDate(d.date,e.time),finish:eventDate(d.date,e.end)})));return all.find(x=>now>=x.start&&now<x.finish)||all.find(x=>x.start>now)||all.at(-1)}
  function localTime(){const p=Object.fromEntries(new Intl.DateTimeFormat('en-GB',{timeZone:tz,hour:'2-digit',minute:'2-digit',hour12:false}).formatToParts(new Date()).map(x=>[x.type,x.value]));return`${p.hour}:${p.minute}`}
  function shiftAfter(day,index,delta){for(let i=index+1;i<day.events.length;i++){if(isFixed(day.events[i]))break;day.events[i].time=fromM(mins(day.events[i].time)+delta);day.events[i].end=fromM(mins(day.events[i].end)+delta)}}
  function reloadSchedule(message){saveSchedule();sessionStorage.setItem('st-v5-message',message);location.reload()}

  function renderCompanion(){
    const host=$('#companionPanel');if(!host)return;const n=currentOrNext(),p=placeById[n.placeId],now=new Date(),dd=p&&pos?hav(pos,p):null;
    const fixed=n.day.events.slice(n.index+(isFixed(n)?0:1)).find(isFixed);let status='Séjour à venir';if(now>=n.start&&now<n.finish)status='Étape en cours';else if(dateFmt.format(now)===n.day.date){const m=Math.round((n.start-now)/60000);status=m>0?`Départ dans ${m} min`:'À démarrer'}
    host.innerHTML=`<article class="companion-card companion-card--focus"><p class="kicker">Décision actuelle</p><h3>${n.title}</h3><div class="companion-metric">${status}</div><p>${p?p.name:n.place}${dd!==null?` · ${dist(dd)} de vous`:''}</p>${p&&pos?`<div class="companion-row"><span>Direction</span><strong>${compass(bearing(pos,p))}</strong></div>`:''}</article><article class="companion-card"><p class="kicker">Contrainte protégée</p><h3>Transport fixe</h3><div class="companion-row"><span>Prochain</span><strong>${fixed?`${fixed.time} · ${fixed.title}`:'Aucun'}</strong></div><div class="companion-row"><span>Audioguide</span><strong>${settings.audioAuto?'Automatique':'Manuel'}</strong></div><div class="companion-row"><span>Visites</span><strong>${Object.keys(visits).length}/${data.places.length}</strong></div><div class="companion-row"><span>Distance GPS</span><strong>${journey.distanceKm.toFixed(1)} km</strong></div></article>`;
  }
  function shiftCurrent(delta){const n=currentOrNext();if(isFixed(n)){toast('Transport fixe : V5 ne le décale pas automatiquement.');return}const e=n.day.events[n.index];e.time=fromM(mins(e.time)+delta);e.end=fromM(mins(e.end)+delta);shiftAfter(n.day,n.index,delta);reloadSchedule(`Programme recalé de ${delta>0?'+':''}${delta} min jusqu’au prochain transport fixe.`)}
  function startNow(){const n=currentOrNext();if(isFixed(n)){toast('Cette étape est un transport fixe : gardez cet horaire.');return}if(dateFmt.format(new Date())!==n.day.date){toast('“Démarrer maintenant” sera actif pendant le séjour.');return}const now=localTime(),delta=mins(now)-mins(n.time);if(Math.abs(delta)>240){toast('Écart trop important : utilisez l’éditeur du programme.');return}const e=n.day.events[n.index];e.time=now;e.end=fromM(mins(e.end)+delta);shiftAfter(n.day,n.index,delta);reloadSchedule('Étape démarrée maintenant · suite flexible recalée.')}
  function recover30(){const n=currentOrNext(),day=n.day;let i=n.index;while(i<day.events.length&&isFixed(day.events[i]))i++;const e=day.events[i];if(!e||mins(e.end)-mins(e.time)<45){toast('Aucune étape flexible assez longue à raccourcir.');return}e.end=fromM(mins(e.end)-30);for(let j=i+1;j<day.events.length;j++){if(isFixed(day.events[j]))break;day.events[j].time=fromM(mins(day.events[j].time)-30);day.events[j].end=fromM(mins(day.events[j].end)-30)}reloadSchedule(`30 min récupérées sur “${e.title}”.`)}

  function audioState(t){if($('#audioState'))$('#audioState').textContent=t;if($('#audioToggle')){$('#audioToggle').textContent=settings.audioAuto?'Auto ON':'Auto OFF';$('#audioToggle').classList.toggle('is-on',settings.audioAuto)}}
  function voice(){const v=speechSynthesis.getVoices();return v.find(x=>/^fr-FR/i.test(x.lang))||v.find(x=>/^fr/i.test(x.lang))||null}
  function speak(p,full=false){if(!p||!('speechSynthesis'in window)){toast('Synthèse vocale indisponible.');return}const text=full?`Vous êtes à ${p.name}. ${p.description||p.note||''} ${p.historyShort||''} ${p.historyLong||''} ${p.arCue||''}`:`Vous approchez de ${p.name}. ${p.historyShort||p.description||p.note||''} ${p.arCue||''}`;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='fr-FR';u.rate=.94;const v=voice();if(v)u.voice=v;u.onstart=()=>audioState(`Lecture : ${p.name}`);u.onend=()=>audioState(`Prêt · ${settings.audioAuto?'automatique actif':'mode manuel'}`);speechSynthesis.speak(u);lastAudioPlace=p;lastAudioId=p.id;lastAudioAt=Date.now()}
  function autoSpeak(p){if(!settings.audioAuto||!p)return;if(lastAudioId===p.id&&Date.now()-lastAudioAt<10*60*1000)return;speak(p,false)}

  function record(type,text,placeId=null,at=new Date().toISOString()){events.push({id:`${Date.now()}-${Math.random()}`,type,text,placeId,at});events=events.slice(-100);write(KEYS.events,events)}
  function markVisited(p){if(!p)return;const now=new Date().toISOString();if(!visits[p.id]){visits[p.id]={placeId:p.id,firstAt:now,lastAt:now,count:1};write(KEYS.visits,visits);record('visit',`Visite de ${p.name}`,p.id,now);toast(`✓ ${p.name} ajouté au souvenir.`);void renderMemory();renderCompanion()}else{visits[p.id].lastAt=now;write(KEYS.visits,visits)}}
  function proximityCheck(){if(!pos)return;for(const p of data.places){const m=hav(pos,p)*1000,arrival=p.arrivalRadius||120,near=p.proximityRadius||450;if(m<=arrival&&proximity[p.id]!=='arrived'){proximity[p.id]='arrived';markVisited(p);autoSpeak(p)}else if(m<=near&&!proximity[p.id]){proximity[p.id]='near';toast(`Vous approchez de ${p.name}.`)}}}
  function onPosition(g){const here={lat:g.coords.latitude,lng:g.coords.longitude,accuracy:g.coords.accuracy||99,ts:g.timestamp};pos=here;if(!journey.startedAt)journey.startedAt=new Date().toISOString();journey.lastAt=new Date().toISOString();if(lastTrack&&here.accuracy<=80){const step=hav(lastTrack,here);if(step>=.003&&step<=.25)journey.distanceKm+=step}lastTrack=here;write(KEYS.journey,journey);proximityCheck();renderCompanion();void renderMemory()}
  function toggleV5Gps(){if(!navigator.geolocation)return;if(v5Watch!==null){navigator.geolocation.clearWatch(v5Watch);v5Watch=null;return}v5Watch=navigator.geolocation.watchPosition(onPosition,()=>{}, {enableHighAccuracy:true,maximumAge:1500,timeout:12000})}

  function openDb(){return new Promise((resolve,reject)=>{const r=indexedDB.open('santa-teresa-v5',1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains('photos'))r.result.createObjectStore('photos',{keyPath:'id',autoIncrement:true})};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
  async function photos(){try{const db=await openDb();return await new Promise((resolve,reject)=>{const tx=db.transaction('photos','readonly'),q=tx.objectStore('photos').getAll();q.onsuccess=()=>resolve(q.result||[]);q.onerror=()=>reject(q.error)})}catch{return[]}}
  async function addPhoto(blob,placeId){const db=await openDb();return await new Promise((resolve,reject)=>{const tx=db.transaction('photos','readwrite'),q=tx.objectStore('photos').add({blob,placeId,at:new Date().toISOString()});q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
  async function compress(file){try{const bmp=await createImageBitmap(file),scale=Math.min(1,1280/Math.max(bmp.width,bmp.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bmp.width*scale);canvas.height=Math.round(bmp.height*scale);canvas.getContext('2d').drawImage(bmp,0,0,canvas.width,canvas.height);bmp.close();return await new Promise(r=>canvas.toBlob(b=>r(b||file),'image/jpeg',.76))}catch{return file}}
  function nearest(max=1){if(!pos)return null;const a=data.places.map(p=>({p,d:hav(pos,p)})).sort((x,y)=>x.d-y.d);return a[0]&&a[0].d<=max?a[0].p:null}
  async function renderMemory(){const ph=await photos(),visited=Object.values(visits).sort((a,b)=>new Date(a.firstAt)-new Date(b.firstAt));objectUrls.forEach(URL.revokeObjectURL);objectUrls=[];if($('#memoryStats'))$('#memoryStats').innerHTML=`<div class="memory-stat"><strong>${visited.length}</strong><small>lieux visités</small></div><div class="memory-stat"><strong>${journey.distanceKm.toFixed(1)}</strong><small>km enregistrés</small></div><div class="memory-stat"><strong>${ph.length}</strong><small>photos personnelles</small></div><div class="memory-stat"><strong>${notes.length}</strong><small>notes</small></div>`;if($('#visitedPlaces'))$('#visitedPlaces').innerHTML=visited.length?visited.map(v=>{const p=placeById[v.placeId];return`<div class="visited-row"><span class="visit-icon">${p?.icon||'✓'}</span><div><strong>${p?.name||v.placeId}</strong><small>${dateTimeFmt.format(new Date(v.firstAt))}</small></div><span>✓</span></div>`}).join(''):'<p class="microcopy">Les visites seront enregistrées automatiquement avec le GPS.</p>';const timeline=[...events,...notes.map(n=>({...n,type:'note'}))].sort((a,b)=>new Date(b.at)-new Date(a.at)).slice(0,30);if($('#memoryTimeline'))$('#memoryTimeline').innerHTML=timeline.length?`<h3 class="subsection-title">Journal du séjour</h3>${timeline.map(e=>`<div class="memory-event"><time>${timeFmt.format(new Date(e.at))}</time><p>${e.type==='visit'?'✓ ':e.type==='photo'?'📷 ':e.type==='note'?'✎ ':''}${esc(e.text)}${e.placeId&&placeById[e.placeId]?` · <strong>${esc(placeById[e.placeId].name)}</strong>`:''}</p></div>`).join('')}`:'';if($('#memoryGallery'))$('#memoryGallery').innerHTML=ph.map(x=>{const u=URL.createObjectURL(x.blob);objectUrls.push(u);return`<article class="memory-photo"><img src="${u}" alt="Souvenir"><div><strong>${esc(placeById[x.placeId]?.name||'Souvenir libre')}</strong><small>${dateTimeFmt.format(new Date(x.at))}</small></div></article>`}).join('')}
  function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
  function dataUrl(blob){return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(r.error);r.readAsDataURL(blob)})}
  async function souvenirHtml(){const ph=await photos(),emb=[];for(const x of ph)emb.push({...x,src:await dataUrl(x.blob)});const visited=Object.values(visits).sort((a,b)=>new Date(a.firstAt)-new Date(b.firstAt));return`<!doctype html><html lang="fr"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Souvenir Santa Teresa</title><style>body{font-family:system-ui;margin:0;background:#fffaf3;color:#15343b}.hero{padding:48px 24px;background:#103f4a;color:white}.wrap{max-width:900px;margin:auto;padding:24px}h1{font-size:42px}.stats{display:flex;gap:10px;flex-wrap:wrap}.stat,.card{background:white;padding:14px;border-radius:16px}.grid,.photos{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.photos img{width:100%;border-radius:16px}@media(max-width:650px){.grid,.photos{grid-template-columns:1fr}}</style><div class="hero"><div class="wrap"><h1>Santa Teresa · notre voyage</h1><p>17–18 septembre 2026 · Carnet Pocket Guide V5</p></div></div><main class="wrap"><div class="stats"><div class="stat"><b>${visited.length}</b><br>lieux</div><div class="stat"><b>${journey.distanceKm.toFixed(1)} km</b><br>parcourus</div><div class="stat"><b>${emb.length}</b><br>photos</div><div class="stat"><b>${notes.length}</b><br>notes</div></div><h2>Lieux visités</h2><div class="grid">${visited.map(v=>{const p=placeById[v.placeId];return`<div class="card"><h3>${esc(p?.name||v.placeId)}</h3><p>${esc(p?.historyShort||'')}</p><small>${esc(dateTimeFmt.format(new Date(v.firstAt)))}</small></div>`}).join('')}</div><h2>Notes</h2>${notes.map(n=>`<div class="card"><p>${esc(n.text)}</p><small>${esc(dateTimeFmt.format(new Date(n.at)))}</small></div>`).join('')}<h2>Photos</h2><div class="photos">${emb.map(x=>`<figure><img src="${x.src}"><figcaption>${esc(placeById[x.placeId]?.name||'Santa Teresa')}</figcaption></figure>`).join('')}</div></main></html>`}
  async function exportSouvenir(share=false){const html=await souvenirHtml(),file=new File([html],'souvenir-santa-teresa-v5.html',{type:'text/html'});if(share&&navigator.share&&navigator.canShare?.({files:[file]})){try{await navigator.share({title:'Souvenir Santa Teresa',files:[file]});return}catch{}}const u=URL.createObjectURL(file),a=document.createElement('a');a.href=u;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000);toast('Carnet souvenir exporté.')}

  $('#startNowBtn')?.addEventListener('click',startNow);$('#plus15Btn')?.addEventListener('click',()=>shiftCurrent(15));$('#plus30Btn')?.addEventListener('click',()=>shiftCurrent(30));$('#recover30Btn')?.addEventListener('click',recover30);
  $('#audioToggle')?.addEventListener('click',()=>{settings.audioAuto=!settings.audioAuto;write(KEYS.settings,settings);audioState(settings.audioAuto?'Automatique activé':'Automatique désactivé');renderCompanion()});
  $('#audioReplay')?.addEventListener('click',()=>speak(lastAudioPlace||nearest(3)||placeById[currentOrNext().placeId],true));$('#audioStop')?.addEventListener('click',()=>{window.speechSynthesis?.cancel();audioState('Lecture arrêtée')});
  $('#locateMe')?.addEventListener('click',toggleV5Gps);
  $('#memoryPhotoInput')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;toast('Préparation de la photo…');const blob=await compress(file),p=nearest(1);await addPhoto(blob,p?.id||null);record('photo','Photo ajoutée au carnet',p?.id||null);e.target.value='';await renderMemory();toast('Photo ajoutée au souvenir.')});
  $('#saveMemoryNote')?.addEventListener('click',()=>{const box=$('#memoryNote'),text=box.value.trim();if(!text)return;const p=nearest(1);notes.push({id:`n-${Date.now()}`,text,placeId:p?.id||null,at:new Date().toISOString()});write(KEYS.notes,notes);box.value='';void renderMemory();toast('Note enregistrée.')});
  $('#exportMemory')?.addEventListener('click',()=>exportSouvenir(false));$('#shareMemory')?.addEventListener('click',()=>exportSouvenir(true));

  const msg=sessionStorage.getItem('st-v5-message');if(msg){sessionStorage.removeItem('st-v5-message');setTimeout(()=>toast(msg),600)}
  if(!('speechSynthesis'in window)){['audioToggle','audioReplay','audioStop'].forEach(id=>{const b=$(`#${id}`);if(b)b.disabled=true});audioState('Synthèse vocale indisponible')}else audioState(settings.audioAuto?'Prêt · lecture automatique active':'Prêt · mode manuel');
  renderCompanion();void renderMemory();
}
