import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';

const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [contract,html,sw,state,actions,context,persistence,memory,routeMemory,proposal,transaction,routeActions,planner,realtime,platform,perception,ar,proactive,entry,bootstrap]=await Promise.all([
  read('docs/PG16_RC1_ACCEPTANCE_CONTRACT.md'),read('pocketguide-16.html'),read('service-worker.js'),read('js/pg16/core/pocketguide-state.js'),read('js/pg16/core/action-registry.js'),read('js/pg16/core/context-engine.js'),read('js/pg16/core/state-persistence.js'),read('js/pg16/memory/memory-store.js'),read('js/pg16/memory/route-memory.js'),read('js/pg16/core/proposal-manager.js'),read('js/pg16/core/transaction-manager.js'),read('js/pg16/route/route-actions.js'),read('js/pg16/planner/planner-engine.js'),read('js/pg16/guide/realtime-session.js'),read('js/pg16/platform/platform.js'),read('js/pg16/perception/perception-engine.js'),read('js/pg16/ar/geo-ar-engine.js'),read('js/pg16/proactive/proactive-engine.js'),read('js/pg16/bootstrap/app-rc-entry.js'),read('js/pg16/bootstrap/app-rc-bootstrap.js')
]);

test('contract explicitly defines all G0-G15 release gates',()=>{for(let i=0;i<=15;i++)assert.match(contract,new RegExp(`G${i} —`));assert.match(contract,/MUST NOT be merged/i);});
test('G0 Premium visual continuity',()=>{for(const token of ['terrain','voice-orb','now-strip','bottom-nav','data-tab="guide"','data-tab="map"','data-tab="route"','data-tab="create"'])assert.match(html,new RegExp(token));assert.doesNotMatch(html,/Alpha 1|Alpha 2|Branche expérimentale/);});
test('G1 single state contains the normative domains',()=>{for(const key of ['user','session','trip','route','location','device','connectivity','perception','conversation','preferences','memory','proposals','ui'])assert.match(state,new RegExp(`${key}:`));assert.match(state,/1\.6\.0-rc1/);});
test('G2 actions encode risk confirmation and common execution',()=>{assert.match(actions,/riskLevel/);assert.match(actions,/confirmation/);assert.match(actions,/async execute/);assert.match(routeActions,/route\.replace/);assert.match(routeActions,/route\.shorten/);});
test('G3 context bootstrap and restoration exist',()=>{assert.match(persistence,/restoreStateSnapshot/);assert.match(bootstrap,/restoreStateSnapshot\(\)/);assert.match(bootstrap,/restoredUsable/);assert.match(context,/current:/);assert.match(context,/next:/);});
test('G4 structured memory supports four scopes, route events and forgetting',()=>{for(const scope of ['working','session','trip','persistent'])assert.match(memory,new RegExp(scope));assert.match(memory,/forgetPreference/);assert.match(routeMemory,/route\.visited/);assert.match(routeMemory,/route\.skipped/);assert.match(routeMemory,/place\.storiesTold/);});
test('G5 conversational focus is explicit',()=>{for(const field of ['currentPlaceId','lastMentionedPlaceId','lastObjectType','lastObjectId'])assert.match(state,new RegExp(field));assert.match(routeActions,/conversation\.focus\.changed/);});
test('G6 proposal transaction rollback confirmation and undo exist',()=>{assert.match(proposal,/beforeState/);assert.match(proposal,/transactionManager\.run/);assert.match(transaction,/rolled_back/);assert.match(transaction,/undo\(\)/);});
test('G7 Planner proposes validated route replacement',()=>{assert.match(planner,/plannerClient\.plan/);assert.match(planner,/action:'route\.replace'/);assert.match(planner,/proposeShortening/);});
test('G8 Realtime is interruptible and structural tools propose',()=>{assert.match(realtime,/RTCPeerConnection/);assert.match(realtime,/response\.cancel/);assert.match(realtime,/propose_skip_current/);assert.match(realtime,/proposalManager\.create/);assert.match(realtime,/plannerEngine\.proposeReplacement/);});
test('G9 perception and platform adapters isolate smartphone capabilities',()=>{assert.match(platform,/requestOrientationPermission/);for(const cap of ['startLocation','startOrientation','openCamera','reset'])assert.match(perception,new RegExp(cap));assert.match(perception,/simulation/);});
test('G10 Geo-AR delegates geometry to deterministic ar-core',()=>{assert.match(ar,/projectPlaces/);assert.match(ar,/haversineKm/);assert.match(ar,/bearingDeg/);assert.doesNotMatch(ar,/fetch\(/);});
test('G11 proactive engine is event driven and cooldown gated',()=>{assert.match(proactive,/globalCooldownMs/);for(const event of ['gps.updated','network.offline','network.online','route.completed'])assert.match(proactive,new RegExp(event.replace('.','\\.')));assert.match(proactive,/off_route/);assert.match(proactive,/gps_degraded/);});
test('G12 offline continuity has persistence and graceful network handling',()=>{assert.match(sw,/pocketguide-v16-rc1-premium/);assert.match(persistence,/pagehide/);assert.match(bootstrap,/network\.offline/);assert.match(bootstrap,/realtimeSession\.disconnect/);});
test('G13 PWA has explicit 1.6 cache and navigation key',()=>{assert.match(sw,/PG16_CACHE='pocketguide-v16-rc1-premium'/);assert.match(sw,/pocketguide-16\.html/);assert.match(sw,/app-rc-entry\.js/);assert.match(sw,/route-memory\.js/);assert.match(sw,/app-rc-bootstrap\.js/);assert.match(sw,/navigationCacheKey/);assert.match(sw,/cacheNameFor/);});
test('G14 simulation suite lists all 24 normative scenarios',async()=>{const sim=await read('tests/pg16-rc1-simulation.test.mjs');for(let i=1;i<=24;i++)assert.match(sim,new RegExp(`G14\\.${i}`));});
test('G15 normal UI hides engineering simulation entry and boots final RC entrypoint',()=>{assert.match(html,/id="startDemo" class="ghost" hidden/);assert.match(html,/app-rc-entry\.js\?v=1\.6\.0rc1/);assert.match(entry,/installRouteMemory\(\)/);assert.match(entry,/app-rc-bootstrap\.js/);assert.match(bootstrap,/serviceWorker\.register/);});
