import test from 'node:test';
import assert from 'node:assert/strict';
import {pocketGuideState} from '../js/pg16/core/pocketguide-state.js';
import {ItineraryStore,MemoryItineraryDriver} from '../js/pg18/storage/itinerary-store.js';
import {fitWithin,resolveAssociation,captureMetadata,savePersonalPhoto} from '../js/pg18/media/photo-capture.js';
import {buildAudiovisualJournal} from '../js/pg18/journal/audiovisual-journal.js';
import {createPortableBundle,createPortableBackupBlob,importPortableBundle,BUNDLE_SCHEMA} from '../js/pg18/backup/portable-backup.js';

const pack={id:'trip-media',title:'Voyage média',places:[{id:'p1',name:'Place',lat:41,lng:9,heroImage:'place.jpg'}],days:[{events:[{id:'e1',placeId:'p1'}]}]};
const itinerary={id:'trip-media',label:'Mon voyage',title:pack.title,status:'in_progress',createdAt:'2026-01-01T00:00:00.000Z',updatedAt:'2026-01-01T00:00:00.000Z',revision:1,routePack:pack,progress:{currentEventId:'e1',nextEventId:null,completedEventIds:[],skippedEventIds:[]},stats:{poiCount:1,mediaCount:0}};
function localStore(){return new ItineraryStore({driver:new MemoryItineraryDriver()});}

test('photo sizing is bounded without distortion',()=>{assert.deepEqual(fitWithin(4000,2000,1600),{width:1600,height:800,scale:.4});assert.deepEqual(fitWithin(800,1200,1600),{width:800,height:1200,scale:1});});
test('association distinguishes current POI, next POI and segment',()=>{const context={currentEventId:'e1',nextEventId:'e2'};assert.deepEqual(resolveAssociation('current',context),{type:'poi',eventId:'e1'});assert.deepEqual(resolveAssociation('next',context),{type:'poi',eventId:'e2'});assert.deepEqual(resolveAssociation('segment',context),{type:'segment',eventId:'e1',nextEventId:'e2'});});
test('capture metadata preserves missing GPS instead of fabricating coordinates',()=>{const meta=captureMetadata({itineraryId:'trip-media',route:{...itinerary.progress,activeId:'trip-media',pack},location:{lat:null,lng:null,accuracy:null}});assert.equal(meta.location.lat,null);assert.equal(meta.location.lng,null);assert.equal(meta.poiId,'p1');});
test('personal photo bytes, thumbnail and measured GPS remain local',async()=>{const store=localStore();await store.saveItinerary(itinerary);pocketGuideState.reset({source:'pg18-media'});pocketGuideState.patch({route:{activeId:'trip-media',pack,currentEventId:'e1',nextEventId:null},location:{lat:41.1,lng:9.1,accuracy:7,heading:90,updatedAt:'2026-01-01T10:00:00.000Z'}},{source:'pg18-media'});const blob=new Blob(['private-photo'],{type:'image/jpeg'}),record=await savePersonalPhoto(blob,{store,caption:'Mon souvenir'});assert.equal(record.blob.size,13);assert.equal(record.thumbnail.size,13);assert.equal(record.location.lat,41.1);assert.equal((await store.listMedia('trip-media')).length,1);});
test('journal preserves official and personal provenance in geographic order',()=>{const media=[{id:'m1',itineraryId:'trip-media',eventId:'e1',poiId:'p1',caption:'Mon détail',capturedAt:'2026-01-01T10:00:00.000Z',blob:new Blob(['x'])}];const entries=buildAudiovisualJournal(itinerary,media);assert.deepEqual(entries.map(entry=>entry.provenance),['RoutePack','Photo personnelle']);assert.equal(entries[1].eventId,'e1');});
test('complete portable export import round trip preserves binary personal media',async()=>{const source=localStore();await source.saveItinerary(itinerary);await source.saveMedia({id:'m1',itineraryId:'trip-media',eventId:'e1',capturedAt:'2026-01-01T10:00:00.000Z',blob:new Blob(['photo-bytes'],{type:'image/jpeg'}),thumbnail:new Blob(['thumb'],{type:'image/jpeg'}),voiceNote:new Blob(['voice'],{type:'audio/webm'})});const bundle=await createPortableBundle('trip-media',{store:source});assert.equal(bundle.schema,BUNDLE_SCHEMA);const backup=await createPortableBackupBlob('trip-media',{store:source}),target=localStore(),result=await importPortableBundle(backup,{store:target,now:()=>1_800_000_000_000});assert.equal(result.media.length,1);assert.equal(await result.media[0].blob.text(),'photo-bytes');assert.equal(await result.media[0].voiceNote.text(),'voice');assert.equal((await target.getItinerary('trip-media')).stats.mediaCount,1);});
test('collision imports as a safe copy and corrupt bundle leaves existing data intact',async()=>{const store=localStore();await store.saveItinerary(itinerary);const bundle={schema:BUNDLE_SCHEMA,itinerary,media:[]},result=await importPortableBundle(JSON.stringify(bundle),{store,now:()=>1_800_000_000_000});assert.equal(result.collision,true);assert.notEqual(result.itinerary.id,'trip-media');await assert.rejects(()=>importPortableBundle('{broken',{store}),/illisible/);assert.ok(await store.getItinerary('trip-media'));});

