import test from 'node:test';
import assert from 'node:assert/strict';
import {pocketGuideState} from '../js/pg16/core/pocketguide-state.js';
import {ItineraryStore,MemoryItineraryDriver} from '../js/pg18/storage/itinerary-store.js';
import {ItineraryManager,itineraryRecordFromRoute} from '../js/pg18/itineraries/itinerary-manager.js';

const pack={id:'route-a',title:'Route A',places:[{id:'p1',name:'Un',lat:41,lng:9},{id:'p2',name:'Deux',lat:41.01,lng:9.01}],days:[{events:[{id:'e1',placeId:'p1'},{id:'e2',placeId:'p2'}]}]};
function store(){return new ItineraryStore({driver:new MemoryItineraryDriver()});}
function loadState(routePack=pack,id=routePack.id){pocketGuideState.reset({source:'pg18-test'});pocketGuideState.patch({route:{activeId:id,title:routePack.title,pack:structuredClone(routePack),currentEventId:'e1',nextEventId:'e2',completedEventIds:[],skippedEventIds:[],remainingMinutes:45}},{source:'pg18-test'});}

test('automatic itinerary record contains exact RoutePack and progress',async()=>{loadState();const record=itineraryRecordFromRoute(pocketGuideState.select('route'));assert.equal(record.id,'route-a');assert.equal(record.status,'planned');assert.equal(record.stats.poiCount,2);assert.equal(record.progress.currentEventId,'e1');assert.deepEqual(record.routePack,pack);});
test('manager saves isolated itineraries without overwriting another route',async()=>{const local=store(),manager=new ItineraryManager({store:local});loadState();await manager.saveCurrent('first');const second={...structuredClone(pack),id:'route-b',title:'Route B'};loadState(second,'route-b');await manager.saveCurrent('second');const items=await local.listItineraries();assert.equal(items.length,2);assert.ok(await local.getItinerary('route-a'));assert.ok(await local.getItinerary('route-b'));});
test('material RoutePack change increments revision while progress save does not',async()=>{const local=store(),manager=new ItineraryManager({store:local});loadState();assert.equal((await manager.saveCurrent()).revision,1);pocketGuideState.patch({route:{completedEventIds:['e1'],currentEventId:'e2',nextEventId:null}},{source:'test'});assert.equal((await manager.saveCurrent()).revision,1);const changed={...structuredClone(pack),title:'Route A enrichie'};pocketGuideState.patch({route:{pack:changed,title:changed.title}},{source:'test'});assert.equal((await manager.saveCurrent()).revision,2);});
test('load resumes exact saved progress and restart is explicit',async()=>{const local=store(),manager=new ItineraryManager({store:local});loadState();pocketGuideState.patch({route:{currentEventId:'e2',nextEventId:null,completedEventIds:['e1']}},{source:'test'});await manager.saveCurrent();pocketGuideState.reset({source:'test'});await manager.load('route-a');assert.equal(pocketGuideState.select('route.currentEventId'),'e2');assert.deepEqual(pocketGuideState.select('route.completedEventIds'),['e1']);await manager.load('route-a',{restart:true});assert.equal(pocketGuideState.select('route.currentEventId'),'e1');assert.deepEqual(pocketGuideState.select('route.completedEventIds'),[]);});
test('duplicate gets new identity and archive/delete include local media',async()=>{const local=store(),manager=new ItineraryManager({store:local});loadState();await manager.saveCurrent();await local.saveMedia({id:'m1',itineraryId:'route-a',capturedAt:'2026-01-01'});const copy=await manager.duplicate('route-a');assert.notEqual(copy.id,'route-a');assert.equal(copy.stats.mediaCount,0);await manager.archive('route-a',true);assert.equal((await local.getItinerary('route-a')).status,'archived');await manager.delete('route-a');assert.equal(await local.getItinerary('route-a'),null);assert.equal((await local.listMedia('route-a')).length,0);});
test('completed journal snapshot is preserved when a later RoutePack revision reuses its id',async()=>{const local=store(),manager=new ItineraryManager({store:local});loadState();pocketGuideState.patch({route:{currentEventId:null,nextEventId:null,completedEventIds:['e1','e2']}},{source:'test'});await manager.saveCurrent();const changed={...structuredClone(pack),title:'Nouvelle visite'};pocketGuideState.patch({route:{pack:changed,title:changed.title,currentEventId:'e1',completedEventIds:[]}},{source:'test'});const fork=await manager.saveCurrent();assert.notEqual(fork.id,'route-a');assert.equal((await local.getItinerary('route-a')).status,'completed');assert.equal((await local.getItinerary('route-a')).title,'Route A');});
