import test from 'node:test';
import assert from 'node:assert/strict';
import {PlanningStageEngine} from '../js/pg22/planning/planning-stage-engine.js';
import {MediaPackEngine} from '../js/pg22/media/media-pack-engine.js';
import {MemoryAudioPackStore,UnifiedAudioBus,UnifiedVoiceService} from '../js/pg22/audio/unified-audio-pack.js';
import {MapModeController} from '../js/pg22/maps/map-mode-controller.js';
import {AvatarRuntime,visemeForCharacter} from '../js/pg22/avatar/avatar-runtime.js';
import {MemoryItineraryDriver,ItineraryStore} from '../js/pg18/storage/itinerary-store.js';
import {createPortableBundle,importPortableBundle} from '../js/pg18/backup/portable-backup.js';
import {buildAudiovisualJournal} from '../js/pg18/journal/audiovisual-journal.js';

const basePack={schemaVersion:'1.0',id:'simulation-v22',title:'Simulation V2.2',subtitle:'Parcours test',timezone:'Europe/Paris',travelers:1,start:'2026-08-26',end:'2026-08-26',places:[{id:'p1',name:'Premier lieu',lat:41.39,lng:9.15,description:'Premier récit.'},{id:'p2',name:'Deuxième lieu',lat:41.391,lng:9.151,description:'Deuxième récit.'}],days:[{date:'2026-08-26',label:'Test',events:[{id:'e1',time:'10:00',end:'10:30',title:'Premier lieu',placeId:'p1'},{id:'e2',time:'10:35',end:'11:00',title:'Deuxième lieu',placeId:'p2'}]}],meta:{source:'simulation'}};
const host=()=>({hidden:false,children:[],replaceChildren(){this.children=[];},append(value){this.children.push(value);}});

test('S1 planning cancellation aborts the active work and preserves the original pack object',()=>{const pack=structuredClone(basePack),engine=new PlanningStageEngine({bus:{emit(){}}}),signal=engine.begin({prompt:'nouvelle excursion'});engine.set('verification');engine.cancel('user');assert.equal(signal.aborted,true);assert.deepEqual(pack,basePack);assert.equal(engine.running,false);});

test('S2 absent media and provider outage still return a complete usable route',async()=>{const engine=new MediaPackEngine({fetchImpl:async()=>{throw new TypeError('offline');}}),result=await engine.enrich(basePack);assert.equal(result.pack.places.length,2);assert.equal(result.mediaPack.status,'empty');assert.equal(result.mediaPack.failures.length,2);});

test('S3 strict offline audio stays textual without invoking browser synthesis',async()=>{let browserVoice=0;globalThis.speechSynthesis={speak(){browserVoice+=1;},cancel(){browserVoice+=1;}};globalThis.SpeechSynthesisUtterance=class{};const service=new UnifiedVoiceService({store:new MemoryAudioPackStore(),fetchImpl:async url=>String(url).startsWith('./data/')?new Response(JSON.stringify({apiBase:'https://offline.test',voice:'marin',offlineAudioMode:'strict'})):new Response('{}',{status:503})}),result=await service.speak('Continuez tout droit.');assert.equal(result.mode,'strict-text');assert.equal(browserVoice,0);delete globalThis.speechSynthesis;delete globalThis.SpeechSynthesisUtterance;});

test('S4 Google unconfigured falls back to OSM without loading its SDK',async()=>{let loads=0;const controller=new MapModeController({loader:{load:async()=>{loads+=1;}},fetchImpl:async()=>new Response('{}')});controller.config={googleMaps:{enabled:false,browserKey:'',cachePolicy:'online-only-no-durable-google-media-cache'}};controller.install({host:host(),osmHost:host(),statusHost:{textContent:'',dataset:{}}});const result=await controller.select('street',{explicit:true,place:basePack.places[0]});assert.equal(result.mode,'osm');assert.equal(result.fallback,true);assert.equal(loads,0);});

test('S5 missing Street View coverage is truthful and returns to OSM',async()=>{const previous=globalThis.google;globalThis.google={maps:{StreetViewService:class{getPanorama(_request,callback){callback(null,'ZERO_RESULTS');}},StreetViewPreference:{NEAREST:'nearest'},StreetViewSource:{OUTDOOR:'outdoor'},StreetViewStatus:{OK:'OK'}}};const controller=new MapModeController();controller.install({host:host(),osmHost:host(),statusHost:{textContent:'',dataset:{}}});controller.ensureGoogle=async()=>{controller.loadedGoogle=true;};const result=await controller.select('street',{explicit:true,place:basePack.places[0]});assert.equal(result.mode,'osm');assert.equal(result.fallback,true);assert.match(result.error.message,/Aucun panorama/);globalThis.google=previous;});

test('S6 incompatible photorealistic 3D falls back to Satellite',async()=>{const previousGoogle=globalThis.google,previousCustom=globalThis.customElements;globalThis.google={maps:{Map:class{constructor(_host,options){this.options=options;}},importLibrary:null}};try{delete globalThis.customElements;}catch{globalThis.customElements=undefined;}const controller=new MapModeController();controller.install({host:host(),osmHost:host(),statusHost:{textContent:'',dataset:{}}});controller.ensureGoogle=async()=>{controller.loadedGoogle=true;};const result=await controller.select('3d',{explicit:true,place:basePack.places[0]});assert.equal(result.mode,'satellite');assert.equal(result.fallback,true);globalThis.google=previousGoogle;globalThis.customElements=previousCustom;});

test('S7 avatar interruption returns immediately to neutral',()=>{const root={setAttribute(_name,value){this.state=value;}},mouth={dataset:{},style:{setProperty(_name,value){this.index=value;}}},label={textContent:''},avatar=new AvatarRuntime();avatar.install({root,mouth,label});avatar.setState('speaking','Je parle');avatar.drive(.9);assert.equal(root.state,'speaking');avatar.interrupt();assert.equal(root.state,'ready');assert.equal(mouth.dataset.viseme,'neutral');avatar.destroy();});

test('S8 portable backup preserves AudioPack blobs but excludes them from the personal journal',async()=>{const source=new ItineraryStore({driver:new MemoryItineraryDriver()}),target=new ItineraryStore({driver:new MemoryItineraryDriver()}),itinerary={id:basePack.id,label:basePack.title,title:basePack.title,status:'planned',createdAt:'2026-08-26T00:00:00Z',updatedAt:'2026-08-26T00:00:00Z',routePack:basePack,progress:{currentEventId:'e1'},stats:{mediaCount:1,audioCount:1}};await source.saveItinerary(itinerary);await source.saveMedia({id:'photo-1',itineraryId:basePack.id,eventId:'e1',kind:'personal-photo',caption:'Souvenir',capturedAt:'2026-08-26T10:00:00Z',blob:new Blob(['photo'],{type:'image/jpeg'})});await source.saveMedia({id:'audio-1',itineraryId:basePack.id,eventId:'p1',kind:'guide-audio',caption:'Premier récit.',capturedAt:'2026-08-26T09:00:00Z',blob:new Blob(['audio'],{type:'audio/mpeg'})});const bundle=await createPortableBundle(basePack.id,{store:source}),imported=await importPortableBundle(JSON.stringify(bundle),{store:target,now:()=>Date.parse('2026-08-26T12:00:00Z')});assert.equal(imported.media.length,2);assert.equal(imported.media.find(item=>item.kind==='guide-audio').blob.type,'audio/mpeg');const journal=buildAudiovisualJournal(imported.itinerary,imported.media);assert.equal(journal.filter(item=>item.kind==='personal').length,1);});

test('S9 Galaxy S22 fallback animates French visemes even when Web Audio reports zero',()=>{let tick=()=>{},clock=500;const root={setAttribute(_name,value){this.state=value;}},mouth={dataset:{},style:{setProperty(_name,value){this.index=value;}}},avatar=new AvatarRuntime({clock:()=>clock,setIntervalImpl:fn=>{tick=fn;return 1;},clearIntervalImpl(){},setTimeoutImpl(){return 1;},clearTimeoutImpl(){}});avatar.install({root,mouth,label:{textContent:''}});avatar.feedTranscript('Bonjour');assert.equal(root.state,'speaking');assert.equal(visemeForCharacter('B'),'mbp');assert.notEqual(mouth.dataset.viseme,'neutral');const first=mouth.dataset.viseme;clock+=100;tick();assert.notEqual(mouth.dataset.viseme,'neutral');assert.ok(first!==mouth.dataset.viseme||mouth.dataset.viseme==='o');avatar.interrupt();assert.equal(mouth.dataset.viseme,'neutral');avatar.destroy();});

test('S10 remote WebRTC audio is analysed as a MediaStream without duplicating playback',()=>{const previous={AudioContext:globalThis.AudioContext,requestAnimationFrame:globalThis.requestAnimationFrame,cancelAnimationFrame:globalThis.cancelAnimationFrame};let streamSources=0,elementSources=0;class FakeAudioContext{constructor(){this.state='suspended';this.destination={};}createAnalyser(){return{fftSize:0,frequencyBinCount:4,connect(){},getByteTimeDomainData(data){data.fill(128);}};}createMediaStreamSource(){streamSources+=1;return{connect(){},disconnect(){}};}createMediaElementSource(){elementSources+=1;return{connect(){},disconnect(){}};}resume(){this.state='running';return Promise.resolve();}}globalThis.AudioContext=FakeAudioContext;globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};const listeners={},element={srcObject:null,addEventListener(type,handler){listeners[type]=handler;}},bus=new UnifiedAudioBus();assert.equal(bus.attachRemote(element),true);element.srcObject={id:'remote-stream'};listeners.playing();assert.equal(streamSources,1);assert.equal(elementSources,0);assert.equal(bus.analysers[0].mode,'media-stream');bus.destroy();globalThis.AudioContext=previous.AudioContext;globalThis.requestAnimationFrame=previous.requestAnimationFrame;globalThis.cancelAnimationFrame=previous.cancelAnimationFrame;});
