import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile,stat} from 'node:fs/promises';
import {PRESENCE_STATES,visibilityVerdict} from '../js/pg23/avatar/living-avatar-runtime.js';
import {SCENE_TYPES} from '../js/pg23/scenes/living-scene-engine.js';

const read=path=>readFile(new URL(`../${path}`,import.meta.url),'utf8');
const [spec,html,css,manifestText,sw,avatar,scenes,scroll,runtime,presence,presentation,sceneStore,performance,v21,audio,media,tripConfig,v22Runtime,shellBootstrap,inheritedBootstrap]=await Promise.all([
  read('docs/PG23_LIVING_COMPANION_TECHNICAL_SPEC.md'),read('pocketguide-v23.html'),read('pocketguide-v23.css'),read('manifest-v23.webmanifest'),read('service-worker.js'),read('js/pg23/avatar/living-avatar-runtime.js'),read('js/pg23/scenes/living-scene-engine.js'),read('js/pg23/scenes/scroll-director.js'),read('js/pg23/bootstrap/living-companion-runtime.js'),read('js/pg23/core/living-presence-machine.js'),read('js/pg23/scenes/route-presentation-director.js'),read('js/pg23/storage/living-scene-store.js'),read('js/pg23/performance/living-performance-monitor.js'),read('js/pg21/bootstrap/app.js'),read('js/pg22/audio/unified-audio-pack.js'),read('js/pg22/media/media-pack-engine.js'),read('js/trip-config.js'),read('js/pg22/bootstrap/audiovisual-runtime.js'),read('js/pg23/bootstrap/app.js'),read('js/pg22/bootstrap/app.js')
]);

test('V2.3 formalise chaque critère bloquant G121 à G150',()=>{for(let gate=121;gate<=150;gate+=1)assert.match(spec,new RegExp(`G${gate}\\b`),`G${gate}`);});

test('V2.3.2 est une PWA indépendante, versionnée et met en cache le runtime complet',()=>{const manifest=JSON.parse(manifestText);assert.match(manifest.start_url,/pocketguide-v23\.html/);assert.match(manifest.name,/V2\.3\.2/);assert.match(html,/data-pg-version="2\.3\.2"/);assert.match(html,/app\.js\?v=2\.3\.2\.11/);assert.match(html,/controllerchange/);assert.match(html,/updateViaCache:'none'/);assert.match(sw,/APP_VERSION='8\.3\.15'/);assert.match(sw,/PG23_CACHE='pocketguide-v23-claire-2-3-2-k'/);assert.match(sw,/AVATAR_CACHE='pocketguide-local-avatar-v9'/);for(const asset of ['pocketguide-v23.html','pocketguide-v23.css','manifest-v23.webmanifest','living-avatar-runtime.js','claire-three-stage.js','living-presence-machine.js','living-performance-monitor.js','living-scene-store.js','route-presentation-director.js','living-scene-engine.js','scroll-director.js'])assert.match(sw,new RegExp(asset.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));});

test('les fonctions héritées V1.8 et V2.2 restent présentes dans la coque',()=>{for(const id of ['companionMic','stopCompanion','simulateJourney','startGps','mapModeBar','openAr','captureMemory','importJourney','journeyLibrary','plannerDialog','proposalDialog','photoDialog','remoteAudio','guideAudio'])assert.match(html,new RegExp(`id="${id}"`),id);for(const mode of ['osm','satellite','street','3d'])assert.match(html,new RegExp(`data-map-mode="${mode}"`));});

test('l’avatar principal possède dix états déterministes et Claire comme seul rendu',()=>{assert.equal(PRESENCE_STATES.length,10);assert.deepEqual(PRESENCE_STATES,['ready','listening','thinking','speaking','presenting','walking','arrived','interrupted','degraded','error']);for(const id of ['humanGuide','avatarPortrait','avatarMouth','avatar3dHost'])assert.match(html,new RegExp(`id="${id}"`));assert.match(html,/Claire se prépare/);assert.match(css,/\.avatar-3d-host/);assert.match(css,/\.avatar-mouth\{display:none!important/);assert.match(css,/data-portrait="compact"[^}]*human-guide/);assert.doesNotMatch(html,/human-guide-v21|human-guide-visemes-v22/);});

test('V2.3.1 arrive directement sur un avatar plein écran et le conserve dans les espaces et en AR',()=>{assert.match(css,/\.living-app \.cinema\{[^}]*min-height:100svh/);assert.match(css,/\.living-app \.human-guide\{[^}]*inset:0[^}]*width:100%[^}]*height:100%/);assert.match(css,/not\(\[data-view="companion"\]\)[^}]*human-guide/);assert.match(css,/\[data-ar="true"\] \.human-guide\{[^}]*opacity:1!important/);assert.doesNotMatch(css,/\[data-ar="true"\] \.human-guide\{opacity:0/);assert.match(v21,/else if\(!livingCompanion\)showDialog\(\$\('#welcomeDialog'\)\)/);});

test('le runtime V2.2 hérité ne peut plus reprendre le titre de la coque V2.3.1',()=>{assert.ok(v22Runtime.includes("const ownsShell=!/^2\\.3/.test"));assert.ok(v22Runtime.includes("if(ownsShell){document.querySelector('.identity strong').textContent='PocketGuide 2.2'"));});

test('un ancien service worker ne peut plus servir les modules critiques à la coque V2.3.2',()=>{assert.match(html,/app\.js\?v=2\.3\.2\.11/);assert.match(shellBootstrap,/pg22\/bootstrap\/app\.js\?v=2\.3\.2\.10/);assert.match(shellBootstrap,/living-companion-runtime\.js\?v=2\.3\.2\.10/);assert.match(inheritedBootstrap,/audiovisual-runtime\.js\?v=2\.3\.2\.1/);assert.match(runtime,/living-performance-monitor\.js\?v=2\.3\.2\.10/);assert.match(shellBootstrap,/MutationObserver/);assert.match(shellBootstrap,/reclaimShellIdentity/);});

test('le panneau d’accueil peut être masqué et se replie automatiquement pour révéler Claire',()=>{for(const id of ['dismissMomentPanel','restoreMomentPanel'])assert.match(html,new RegExp(`id="${id}"`));assert.match(css,/\.living-app \.moment-panel\[hidden\]\{display:none!important\}/);assert.match(runtime,/scheduleCollapse\(5500\)/);assert.match(runtime,/pg23\.avatar\.engine\.active/);});

test('le laboratoire autonome couvre huit visèmes et refuse les faux succès audio',async()=>{for(const id of ['lipSyncLabDialog','labAvatar','labAvatarPortrait','labAvatarMouth','labVerdict','labViseme','labChanges','labVisibility','labVersion','labState','labMode','labSource','labAudio','labLatency','labFcp','labTouch','labFps','labMemory','labBattery','labVideo','testSilentLips','testFrenchLips','testMarinLips'])assert.match(html,new RegExp(`id="${id}"`),id);assert.match(avatar,/runSilent\(\)/);assert.match(avatar,/voice\?\.spoken/);assert.match(avatar,/voice-unavailable/);assert.match(audio,/pg22\.audio\.play\.failed/);for(const code of ['hidden','out-of-frame','still','visible'])assert.match(avatar,new RegExp(`code:'${code}'`));assert.equal(visibilityVerdict({display:'none'}).code,'hidden');const image=await stat(new URL('../assets/companion/human-guide-visemes-v22.png',import.meta.url));assert.ok(image.size>100_000);});

test('le fil vivant supporte toutes les scènes normatives, la persistance locale et la reprise humaine',()=>{assert.equal(SCENE_TYPES.length,13);for(const type of ['speech','thinking','route','media','poi','map','direction','arrival','preview','memory','consent','continuity','error'])assert.ok(SCENE_TYPES.includes(type));for(const id of ['livingFlow','sceneStream','sceneCount','resumeScenes'])assert.match(html,new RegExp(`id="${id}"`));assert.match(scenes,/restore\(scopeId/);assert.match(sceneStore,/localStorage/);assert.match(sceneStore,/scene\?\.persist/);assert.match(scroll,/human-interaction/);assert.match(scroll,/dialog-open/);assert.match(scroll,/reduced-motion/);});

test('les moteurs réels Planner, média, GPS, mémoire et aperçu alimentent les scènes',()=>{for(const event of ['pg22.planning.stage','pg22.media.progress','proposal.created','guidance.snapshot','media.personal.saved','network.offline','companion.realtime.error'])assert.match(runtime,new RegExp(event.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')));assert.match(runtime,/createRouteScene/);assert.match(runtime,/installPreviewHook/);assert.match(runtime,/deterministic-gps/);});

test('la demande d’itinéraire déclenche une présentation POI par POI et un outil Realtime',()=>{assert.match(runtime,/PRESENT_ROUTE/);assert.match(runtime,/pg23\.present_route/);assert.match(runtime,/present_journey/);assert.match(presentation,/places\.forEach/);assert.match(presentation,/type:image\?'media':'poi'/);assert.match(presentation,/mediaStatus:verified\?'verified'/);assert.match(presentation,/type:'map'/);});

test('aucun média touristique manquant ne peut être présenté comme une photographie valide',()=>{assert.doesNotMatch(tripConfig,/modesto:\{image:'assets\/photos\/modesto\.svg'/);assert.match(tripConfig,/modesto:\{image:'',credit:null,page:null,exact:false/);assert.match(v21,/const image=photo\.page&&photo\.image\?photo\.image:''/);assert.match(v21,/media:image\?\[/);});

test('les contrats manquants G124 G128 G129 G147 et G149 sont instrumentés',()=>{for(const event of ['pg23.lipsync.started','pg23.lipsync.stopped','pg23.lipsync.frame','pg23.lipsync.diagnostic'])assert.match(avatar,new RegExp(event.replaceAll('.','\\.')));assert.match(presence,/sequence:this\.sequence/);assert.match(presence,/source:String/);assert.match(presence,/reason:String/);for(const metric of ['firstRenderMs','firstContentfulPaintMs','lastTouchMs','lastLipMs','sampledFps','heapBytes','battery','activeVideoDecoders'])assert.match(performance,new RegExp(metric));assert.match(audio,/timestamp-this\.lastSampleAt>=33/);assert.match(audio,/this\.idleFrames>=30/);assert.match(runtime,/playbackSnapshot/);});

test('accessibilité, vie privée et limites des fournisseurs restent explicites',()=>{assert.match(html,/aria-live="polite"/);assert.match(html,/Rien n’est envoyé automatiquement/);assert.match(html,/contacte Google Maps/);assert.match(css,/min-height:48px/);assert.match(css,/prefers-reduced-motion:reduce/);assert.match(spec,/Galaxy S22 validé.*interdite/i);assert.match(runtime,/const VERSION='2\.3\.2'/);assert.doesNotMatch(runtime,/api[_-]?key\s*[:=]/i);assert.match(media,/mediaSearchQueries/);});
