import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
const root=new URL('../',import.meta.url);const read=path=>readFile(new URL(path,root),'utf8');

test('P1: un seul moteur applicatif principal est chargé',async()=>{const html=await read('index.html');assert.match(html,/type="module" src="js\/app\.js"/);assert.doesNotMatch(html,/js\/v5\.js/);assert.doesNotMatch(html,/v4b-bootstrap\.js/)});
test('P2: navigation pédestre et moteur de contraintes sont présents',async()=>{const app=await read('js/app.js');assert.match(app,/travelmode=walking/);assert.match(app,/shiftFlexibleBlock/);assert.match(app,/navigator\.geolocation\.watchPosition/);assert.equal((app.match(/watchPosition/g)||[]).length,1)});
test('V1.4.8: GeoAR instrumentée utilise caméra, GPS et orientation',async()=>{const html=await read('index.html'),ar=await read('js/ar-v148.js');assert.match(html,/id="arStage"/);assert.match(html,/js\/ar-v148\.js/);assert.doesNotMatch(html,/js\/ar-v6\.js/);assert.match(ar,/getUserMedia/);assert.match(ar,/getCurrentPosition/);assert.match(ar,/DeviceOrientationEvent/);assert.match(ar,/watchPosition/);assert.match(ar,/travelmode=walking/)});
test('V1.4.8: WebXR est distingué de la GeoAR et possède un test de session',async()=>{const ar=await read('js/ar-v148.js');assert.match(ar,/isSessionSupported\?\.\('immersive-ar'\)/);assert.match(ar,/requestSession\('immersive-ar'/);assert.match(ar,/WebXR détecté · Geo‑AR inactive/);assert.match(ar,/webxrSessionOk/)});
test('V1.4.8: simulateur AR permet test hors site avec position virtuelle et rotation',async()=>{const ar=await read('js/ar-v148.js'),core=await read('js/ar-core.js');assert.match(ar,/startSimulation/);assert.match(ar,/nextSimulationPlace/);assert.match(ar,/setInterval/);assert.match(ar,/arsim/);assert.match(core,/simulatedPositionForPlace/);assert.match(core,/projectPlaces/);assert.match(core,/deltaHeading/)});
test('V1.4.8: AR gère retour Android, ciblage et diagnostic runtime',async()=>{const ar=await read('js/ar-v148.js'),css=await read('ar-v6.css');assert.match(ar,/history\.pushState\(\{pocketGuideAR:true\}/);assert.match(ar,/addEventListener\('popstate'/);assert.match(ar,/refreshControls/);assert.match(ar,/aria-disabled/);assert.match(ar,/santaTeresaS22Audit/);assert.match(css,/min-height:48px/);assert.match(css,/overscroll-behavior:none/)});
test('V6.0.5: diagnostic S22 autonome est accessible',async()=>{const diag=await read('diagnostic-s22.html');assert.match(diag,/id="run"/);assert.match(diag,/getCurrentPosition/);assert.match(diag,/getUserMedia/);assert.match(diag,/deviceorientation/);assert.match(diag,/toBlob/)});
test('V6.0.8: l’overlay permission AR respecte hidden sur Android',async()=>{const fix=await read('js/s22-fixes.js'),css=await read('ar-v6.css');assert.match(fix,/enforceArPermissionHidden/);assert.match(fix,/MutationObserver/);assert.match(fix,/s22PlayGuard='6\.0\.8'/);assert.match(css,/\.ar-permission\[hidden\]\{display:none!important\}/)});
test('V1.4.8: PWA met en cache moteur GeoAR, simulateur et Studio',async()=>{const sw=await read('service-worker.js');assert.match(sw,/pocketguide-engine-v1-4-8b/);assert.match(sw,/engine\.html/);assert.match(sw,/studio-148\.html/);assert.match(sw,/ar-core\.js/);assert.match(sw,/ar-v148\.js/);assert.doesNotMatch(sw,/\.\/js\/ar-v6\.js/);assert.match(sw,/route-bootstrap\.js/);assert.match(sw,/event\.request\.mode==='navigate'/);assert.match(sw,/cache:'no-store'/)});
